import type { LootItem } from '../../types.js';
import { srdItems } from '../srd/index.js';

export const lootTable: LootItem[] = [
  // Shared SRD equipment available in this campaign.
  ...srdItems(
    'dagger',
    'dart',
    'handaxe',
    'greataxe',
    'longsword',
    'shortsword',
    'rapier',
    'mace',
    'quarterstaff',
    'longbow',
    'leather_armor',
    'studded_leather',
    'scale_mail',
    'chain_mail',
    'shield',
    'healing_potion',
    'holy_symbol',
    'component_pouch'
  ),
  // Campaign-specific quest items.
  {
    id: 'guild_ledger',
    name: 'Guild Ledger',
    weight: 3,
    desc: "A waterlogged ledger bearing the Merchant Guild's stamp — evidence of the missing shipment.",
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['ledger', 'book', 'shipping records'],
  },
  {
    id: 'shadow_evidence',
    name: 'Incriminating Letter',
    weight: 1,
    desc: "A letter bearing Captain Vane's seal, arranging bribes with the bandits.",
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['letter', 'evidence'],
  },
  {
    id: 'moonstone_amulet',
    name: 'Moonstone Amulet',
    weight: 2,
    desc: 'A silver amulet set with a glowing moonstone. Grants +1 to Wisdom saving throws.',
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: '+1_wis_save',
    requiresAttunement: true,
    aliases: ['amulet', 'moonstone'],
  },
  {
    id: 'stolen_shipment',
    name: 'Stolen Guild Cargo',
    weight: 6,
    desc: "A crate stamped with the Merchant Guild's mark — part of the shipment raided from the Old Road. Aldric will want this back.",
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['cargo', 'crate', 'shipment', 'goods'],
  },
];

export const loot: Record<string, LootItem> = {
  dungeon_antechamber: {
    id: 'healing_potion',
    name: 'Healing Potion',
    weight: 4,
    desc: 'A crimson vial.',
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: '2d4+2',
    effect: null,
    aliases: ['potion'],
  },
  dungeon_offering_chamber: {
    id: 'guild_ledger',
    name: 'Guild Ledger',
    weight: 3,
    desc: "A waterlogged ledger bearing the Guild's stamp.",
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['ledger'],
  },
  dungeon_ossuary: {
    id: 'healing_potion',
    name: 'Healing Potion',
    weight: 4,
    desc: 'A crimson vial.',
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: '2d4+2',
    effect: null,
    aliases: ['potion'],
  },
  dungeon_crypt_throne: {
    id: 'moonstone_amulet',
    name: 'Moonstone Amulet',
    weight: 2,
    desc: 'A glowing moonstone amulet, sacred to Selûne.',
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: '+1_wis_save',
    requiresAttunement: true,
    aliases: ['amulet'],
  },
  bandit_camp: {
    id: 'healing_potion',
    name: 'Healing Potion',
    weight: 4,
    desc: 'A crimson vial, looted from the wagon.',
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: '2d4+2',
    effect: null,
    aliases: ['potion'],
  },
  bandit_tent: {
    id: 'stolen_shipment',
    name: 'Stolen Guild Cargo',
    weight: 6,
    desc: "A crate stamped with the Merchant Guild's mark — the raided Old Road shipment.",
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['cargo', 'crate', 'shipment', 'goods'],
  },
};
