import type { LootItem } from '../../types.js';

// Shared SRD 5.2.1 equipment definitions.
//
// SRD weapons, armor, and adventuring gear are universal — a Longsword in
// Vale of Shadows is the same Longsword as in Whispering Pines. Pansori
// previously duplicated these definitions across every campaign context,
// which drifted (different weights / descriptions / aliases for the same
// item). This registry is the single source of truth.
//
// Contexts compose their `lootTable` from this registry plus their own
// custom items, and limit which SRD items are available by selecting ids:
//
//   lootTable: [
//     ...srdItems('dagger', 'longsword', 'chain_mail', 'shield', 'healing_potion'),
//     myCampaignRelic,                       // custom item, campaign-only
//   ]
//
// A campaign can override an SRD item by placing its own entry with the same
// id AFTER the spread (last-wins on `lootTable.find`), but the default is to
// share the canonical definition so the mechanics stay consistent.
//
// Item IDs match the SRD 5.2.1 names. Mechanical fields (damage, mastery,
// armor class, etc.) follow RAW (Battleaxe = Topple, per the SRD weapon table).
export const SRD_ITEMS: Record<string, LootItem> = {
  // ─── Simple melee weapons ──────────────────────────────────────────────────
  dagger: {
    id: 'dagger',
    value: 2,
    name: 'Dagger',
    desc: '1d4 piercing, finesse, light, thrown',
    weight: 5,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    finesse: true,
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['dagger', 'knife'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'nick',
  },
  handaxe: {
    id: 'handaxe',
    value: 5,
    name: 'Handaxe',
    desc: '1d6 slashing, light, thrown',
    weight: 5,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['handaxe', 'hand axe', 'hatchet'],
    weaponType: 'simple',
    damageType: 'slashing',
    mastery: 'vex',
  },
  quarterstaff: {
    id: 'quarterstaff',
    value: 1,
    name: 'Quarterstaff',
    desc: '1d6 bludgeoning one-handed (1d8 two-handed)',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    versatileDamage: '1d8',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['quarterstaff', 'staff', 'quarter staff'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'topple',
  },
  mace: {
    id: 'mace',
    value: 5,
    name: 'Mace',
    desc: '1d6 bludgeoning',
    weight: 8,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['mace'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'sap',
  },
  spear: {
    id: 'spear',
    value: 1,
    name: 'Spear',
    desc: '1d6 piercing one-handed (1d8 two-handed), thrown 20/60',
    weight: 3,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    versatileDamage: '1d8',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['spear'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'sap',
    thrown: { normalRange: 20, longRange: 60 },
  },
  dart: {
    id: 'dart',
    value: 1,
    name: 'Dart',
    desc: '1d4 piercing, finesse, thrown',
    weight: 1,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    finesse: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['dart', 'darts'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'vex',
  },

  club: {
    id: 'club',
    value: 1,
    name: 'Club',
    desc: '1d4 bludgeoning, light',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['club', 'cudgel'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'slow',
  },
  greatclub: {
    id: 'greatclub',
    value: 1,
    name: 'Greatclub',
    desc: '1d8 bludgeoning, two-handed',
    weight: 10,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['greatclub', 'great club'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'push',
  },
  javelin: {
    id: 'javelin',
    value: 1,
    name: 'Javelin',
    desc: '1d6 piercing, thrown 30/120',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['javelin'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'slow',
    thrown: { normalRange: 30, longRange: 120 },
  },
  light_hammer: {
    id: 'light_hammer',
    value: 2,
    name: 'Light Hammer',
    desc: '1d4 bludgeoning, light, thrown 20/60',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['light hammer', 'light_hammer', 'throwing hammer'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'nick',
    thrown: { normalRange: 20, longRange: 60 },
  },
  sickle: {
    id: 'sickle',
    value: 1,
    name: 'Sickle',
    desc: '1d4 slashing, light',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['sickle'],
    weaponType: 'simple',
    damageType: 'slashing',
    mastery: 'nick',
  },

  // ─── Simple ranged weapons ─────────────────────────────────────────────────
  shortbow: {
    id: 'shortbow',
    value: 25,
    name: 'Shortbow',
    desc: '1d6 piercing, ranged (80/320)',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['shortbow', 'short bow'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'vex',
  },
  light_crossbow: {
    id: 'light_crossbow',
    value: 25,
    name: 'Light Crossbow',
    desc: '1d8 piercing, ranged (80/320), loading, two-handed',
    weight: 5,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['light crossbow', 'crossbow', 'light_crossbow'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'slow',
    loading: true,
  },

  sling: {
    id: 'sling',
    value: 1,
    name: 'Sling',
    desc: '1d4 bludgeoning, ranged (30/120)',
    weight: 1,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['sling'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'slow',
  },

  // ─── Martial melee weapons ─────────────────────────────────────────────────
  shortsword: {
    id: 'shortsword',
    value: 10,
    name: 'Shortsword',
    desc: '1d6 piercing, finesse, light',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    finesse: true,
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['shortsword', 'short sword'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'vex',
  },
  rapier: {
    id: 'rapier',
    value: 25,
    name: 'Rapier',
    desc: '1d8 piercing, finesse',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    finesse: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['rapier'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'vex',
  },
  longsword: {
    id: 'longsword',
    value: 15,
    name: 'Longsword',
    desc: '1d8 slashing (1d10 two-handed), versatile',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    versatileDamage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['longsword', 'long sword', 'sword'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'sap',
  },
  greatsword: {
    id: 'greatsword',
    value: 50,
    name: 'Greatsword',
    desc: '2d6 slashing, heavy, two-handed',
    weight: 10,
    type: 'weapon',
    slot: 'weapon',
    damage: '2d6',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['greatsword', 'great sword'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'graze',
    heavy: true,
  },
  battleaxe: {
    id: 'battleaxe',
    value: 10,
    name: 'Battleaxe',
    desc: '1d8 slashing (1d10 two-handed), versatile, Topple mastery',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    versatileDamage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['battleaxe', 'battle axe', 'axe'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'topple',
  },
  greataxe: {
    id: 'greataxe',
    value: 30,
    name: 'Greataxe',
    desc: '1d12 slashing, heavy, two-handed, Cleave mastery',
    weight: 7,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d12',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['greataxe', 'great axe'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'cleave',
    heavy: true,
  },
  glaive: {
    id: 'glaive',
    value: 20,
    name: 'Glaive',
    desc: '1d10 slashing, heavy, two-handed, reach (10 ft)',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['glaive'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'graze',
    heavy: true,
    reach: true,
  },
  halberd: {
    id: 'halberd',
    value: 20,
    name: 'Halberd',
    desc: '1d10 slashing, heavy, two-handed, reach (10 ft), Cleave mastery',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['halberd'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'cleave',
    heavy: true,
    reach: true,
  },
  pike: {
    id: 'pike',
    value: 5,
    name: 'Pike',
    desc: '1d10 piercing, heavy, two-handed, reach (10 ft)',
    weight: 18,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['pike'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'push',
    heavy: true,
    reach: true,
  },
  warhammer: {
    id: 'warhammer',
    value: 15,
    name: 'Warhammer',
    desc: '1d8 bludgeoning (1d10 two-handed), versatile',
    weight: 5,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    versatileDamage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['warhammer', 'hammer'],
    weaponType: 'martial',
    damageType: 'bludgeoning',
    mastery: 'push',
  },

  flail: {
    id: 'flail',
    value: 10,
    name: 'Flail',
    desc: '1d8 bludgeoning',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['flail'],
    weaponType: 'martial',
    damageType: 'bludgeoning',
    mastery: 'sap',
  },
  lance: {
    id: 'lance',
    value: 10,
    name: 'Lance',
    desc: '1d10 piercing, heavy, reach (10 ft), two-handed unless mounted',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['lance'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'topple',
    heavy: true,
    reach: true,
  },
  maul: {
    id: 'maul',
    value: 10,
    name: 'Maul',
    desc: '2d6 bludgeoning, heavy, two-handed',
    weight: 10,
    type: 'weapon',
    slot: 'weapon',
    damage: '2d6',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['maul'],
    weaponType: 'martial',
    damageType: 'bludgeoning',
    mastery: 'topple',
    heavy: true,
  },
  morningstar: {
    id: 'morningstar',
    value: 15,
    name: 'Morningstar',
    desc: '1d8 piercing',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['morningstar', 'morning star'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'sap',
  },
  scimitar: {
    id: 'scimitar',
    value: 25,
    name: 'Scimitar',
    desc: '1d6 slashing, finesse, light',
    weight: 3,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    finesse: true,
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['scimitar'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'nick',
  },
  trident: {
    id: 'trident',
    value: 5,
    name: 'Trident',
    desc: '1d8 piercing (1d10 two-handed), versatile, thrown 20/60',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    versatileDamage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['trident'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'topple',
    thrown: { normalRange: 20, longRange: 60 },
  },
  war_pick: {
    id: 'war_pick',
    value: 5,
    name: 'War Pick',
    desc: '1d8 piercing (1d10 two-handed), versatile',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    versatileDamage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['war pick', 'war_pick', 'warpick'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'sap',
  },
  whip: {
    id: 'whip',
    value: 2,
    name: 'Whip',
    desc: '1d4 slashing, finesse, reach (10 ft)',
    weight: 3,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    finesse: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['whip'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'slow',
    reach: true,
  },

  // ─── Martial ranged weapons ────────────────────────────────────────────────
  longbow: {
    id: 'longbow',
    value: 50,
    name: 'Longbow',
    desc: '1d8 piercing, heavy, ranged (150/600)',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['longbow', 'long bow'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'slow',
    heavy: true,
  },
  hand_crossbow: {
    id: 'hand_crossbow',
    value: 75,
    name: 'Hand Crossbow',
    desc: '1d6 piercing, light, ranged (30/120), loading',
    weight: 3,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['hand crossbow', 'hand_crossbow', 'crossbow_hand'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'vex',
    light: true,
    loading: true,
  },
  heavy_crossbow: {
    id: 'heavy_crossbow',
    value: 50,
    name: 'Heavy Crossbow',
    desc: '1d10 piercing, heavy, ranged (100/400), loading, two-handed',
    weight: 18,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['heavy crossbow', 'heavy_crossbow'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'push',
    heavy: true,
    loading: true,
  },

  blowgun: {
    id: 'blowgun',
    value: 10,
    name: 'Blowgun',
    desc: '1 piercing, ranged (25/100), loading',
    weight: 1,
    type: 'weapon',
    slot: 'weapon',
    damage: '1',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['blowgun', 'blow gun'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'vex',
    loading: true,
  },
  musket: {
    id: 'musket',
    value: 500,
    name: 'Musket',
    desc: '1d12 piercing, ranged (40/120), loading, two-handed',
    weight: 10,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d12',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['musket'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'slow',
    loading: true,
  },
  pistol: {
    id: 'pistol',
    value: 250,
    name: 'Pistol',
    desc: '1d10 piercing, ranged (30/90), loading',
    weight: 3,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['pistol', 'flintlock'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'vex',
    loading: true,
  },

  // ─── Armor ─────────────────────────────────────────────────────────────────
  padded_armor: {
    id: 'padded_armor',
    value: 5,
    name: 'Padded Armor',
    desc: 'AC 11 + DEX modifier, light armor (stealth disadvantage)',
    weight: 8,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 11,
    armorCategory: 'light',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['padded armor', 'padded'],
  },
  leather_armor: {
    id: 'leather_armor',
    value: 10,
    name: 'Leather Armor',
    desc: 'AC 11 + DEX modifier, light armor',
    weight: 10,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 11,
    armorCategory: 'light',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['leather armor', 'leather'],
  },
  studded_leather: {
    id: 'studded_leather',
    value: 45,
    name: 'Studded Leather',
    desc: 'AC 12 + DEX modifier, light armor',
    weight: 13,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 12,
    armorCategory: 'light',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['studded leather', 'studded'],
  },
  chain_shirt: {
    id: 'chain_shirt',
    value: 50,
    name: 'Chain Shirt',
    desc: 'AC 13 + DEX (max +2), medium armor',
    weight: 20,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 13,
    dexCapToAc: 2,
    armorCategory: 'medium',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['chain shirt'],
  },
  scale_mail: {
    id: 'scale_mail',
    value: 50,
    name: 'Scale Mail',
    desc: 'AC 14 + DEX (max +2), medium armor',
    weight: 6,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 14,
    dexCapToAc: 2,
    armorCategory: 'medium',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['scale mail', 'scale', 'scalemail'],
  },
  hide_armor: {
    id: 'hide_armor',
    value: 10,
    name: 'Hide Armor',
    desc: 'AC 12 + DEX (max +2), medium armor',
    weight: 12,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 12,
    dexCapToAc: 2,
    armorCategory: 'medium',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['hide armor', 'hide'],
  },
  breastplate: {
    id: 'breastplate',
    value: 400,
    name: 'Breastplate',
    desc: 'AC 14 + DEX (max +2), medium armor',
    weight: 20,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 14,
    dexCapToAc: 2,
    armorCategory: 'medium',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['breastplate', 'breast plate'],
  },
  half_plate: {
    id: 'half_plate',
    value: 750,
    name: 'Half Plate Armor',
    desc: 'AC 15 + DEX (max +2), medium armor (stealth disadvantage)',
    weight: 40,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 15,
    dexCapToAc: 2,
    armorCategory: 'medium',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['half plate', 'half_plate', 'half plate armor'],
  },
  chain_mail: {
    id: 'chain_mail',
    value: 75,
    name: 'Chain Mail',
    desc: 'AC 16, heavy armor (STR 13 required)',
    weight: 55,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 16,
    dexCapToAc: 0,
    armorCategory: 'heavy',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['chain mail', 'chainmail'],
  },
  plate_armor: {
    id: 'plate_armor',
    value: 1500,
    name: 'Plate Armor',
    desc: 'AC 18, heavy armor (STR 15 required)',
    weight: 65,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 18,
    dexCapToAc: 0,
    armorCategory: 'heavy',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['plate armor', 'plate'],
  },
  ring_mail: {
    id: 'ring_mail',
    value: 30,
    name: 'Ring Mail',
    desc: 'AC 14, heavy armor (stealth disadvantage)',
    weight: 40,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 14,
    dexCapToAc: 0,
    armorCategory: 'heavy',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['ring mail', 'ringmail'],
  },
  splint_armor: {
    id: 'splint_armor',
    value: 200,
    name: 'Splint Armor',
    desc: 'AC 17, heavy armor (STR 15 required, stealth disadvantage)',
    weight: 60,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 17,
    dexCapToAc: 0,
    armorCategory: 'heavy',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['splint', 'splint armor', 'splint mail'],
  },
  shield: {
    id: 'shield',
    value: 10,
    name: 'Shield',
    desc: '+2 AC while equipped',
    weight: 12,
    type: 'armor',
    slot: 'shield',
    damage: null,
    armorCategory: 'shield',
    ac_bonus: 2,
    heal: null,
    effect: null,
    aliases: ['shield'],
  },

  // ─── Adventuring gear / consumables ─────────────────────────────────────────
  healing_potion: {
    id: 'healing_potion',
    value: 50,
    name: 'Healing Potion',
    desc: 'Restores 2d4+2 HP when consumed.',
    weight: 2,
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: '2d4+2',
    effect: null,
    aliases: ['healing potion', 'potion', 'health potion'],
  },
  healers_kit: {
    // Healer's Kit (SRD) — bandages, splints, and salves. Used (an action) to
    // STABILIZE a dying creature: it stops rolling death saves. Reusable (RAW it
    // has 10 charges; pansori doesn't yet track per-use charges, so it isn't
    // consumed). Wired via the `stabilize` effect in handleUse.
    id: 'healers_kit',
    value: 5,
    name: "Healer's Kit",
    desc: 'Bag of bandages, splints, and salves. Use an action to stabilize a dying creature (stops its death saves).',
    weight: 3,
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: 'stabilize',
    aliases: ['healers kit', "healer's kit", 'healers_kit'],
  },
  holy_symbol: {
    id: 'holy_symbol',
    value: 5,
    name: 'Holy Symbol',
    desc: 'A holy symbol that serves as a divine spellcasting focus.',
    weight: 2,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: 'spellcasting_focus',
    aliases: ['holy symbol', 'symbol', 'holy focus'],
  },
  torch: {
    // SRD light source — held in the off hand. While equipped it sheds bright
    // light in a 20-ft radius (dim to 40 ft); wired into combat lighting via a
    // `light` worn effect synced onto the bearer's entity at combat start, so a
    // torch-bearer negates the darkness penalty around them. Mundane, so the
    // Darkness spell can't snuff it (it just can't pierce magical darkness).
    id: 'torch',
    value: 1,
    name: 'Torch',
    desc: 'Sheds bright light in a 20-foot radius and dim light for an additional 20 feet. Burns for 1 hour.',
    weight: 1,
    type: 'misc',
    slot: 'off_hand',
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['torch'],
    wornEffects: [{ kind: 'light', radiusFt: 20 }],
  },
  hooded_lantern: {
    // SRD light source — a brighter, steadier alternative to the Torch. Bright
    // light 30 ft, dim to 60 ft. Same `light` worn-effect wiring.
    id: 'hooded_lantern',
    value: 5,
    name: 'Hooded Lantern',
    desc: 'Sheds bright light in a 30-foot radius and dim light for an additional 30 feet. Burns 6 hours on a flask of oil.',
    weight: 2,
    type: 'misc',
    slot: 'off_hand',
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['hooded lantern', 'lantern'],
    wornEffects: [{ kind: 'light', radiusFt: 30 }],
  },
  component_pouch: {
    id: 'component_pouch',
    value: 25,
    name: 'Component Pouch',
    desc: 'A leather pouch of spellcasting components.',
    weight: 2,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: 'spellcasting_focus',
    aliases: ['component pouch', 'pouch', 'spell components'],
  },
  bullseye_lantern: {
    // SRD light source — a focused beam. Modeled as a 60-ft bright radius (the
    // RAW 60-ft cone simplified to a radius), dim to 120 ft. Same `light`
    // worn-effect wiring as the Torch / Hooded Lantern.
    id: 'bullseye_lantern',
    value: 10,
    name: 'Bullseye Lantern',
    desc: 'Casts bright light in a 60-foot cone and dim light for an additional 60 feet. Burns 6 hours on a flask of oil.',
    weight: 2,
    type: 'misc',
    slot: 'off_hand',
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['bullseye lantern', 'bullseye'],
    wornEffects: [{ kind: 'light', radiusFt: 60 }],
  },

  // ─── Consumable gear ─────────────────────────────────────────────────────────
  antitoxin: {
    // SRD — drink to gain Advantage on the next save vs poison. Reuses the
    // consumable `con_advantage` effect (handleUse rolls a CON save w/ advantage).
    id: 'antitoxin',
    value: 50,
    name: 'Antitoxin',
    desc: 'Drink as an action to gain advantage on your next saving throw against poison for 1 hour.',
    weight: 0,
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: 'con_advantage',
    aliases: ['antitoxin', 'anti-toxin'],
  },
  rations: {
    id: 'rations',
    value: 1,
    name: 'Rations',
    desc: 'A day of dried food. Eat to stave off hunger on the road.',
    weight: 2,
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    useNarrative: 'You eat a day of trail rations — dry, but filling.',
    aliases: ['rations', 'trail rations', 'ration'],
  },
  oil_flask: {
    id: 'oil_flask',
    value: 1,
    name: 'Oil (flask)',
    desc: 'A flask of lamp oil. Refuels a lantern (6 hours) or can be poured out and set alight.',
    weight: 1,
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    useNarrative:
      'You ready the flask of oil — pour it to refuel a lantern, or spread it to be lit.',
    aliases: ['oil', 'oil flask', 'flask of oil', 'lamp oil'],
  },
  acid_vial: {
    // SRD thrown splash weapon — throw at a foe (DEX ranged attack); on a hit,
    // 2d6 acid. See the `throw_item` action.
    id: 'acid_vial',
    value: 25,
    name: 'Acid (vial)',
    desc: 'A vial of corrosive acid. Throw it at a creature (ranged attack) for 2d6 acid damage on a hit.',
    weight: 1,
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['acid', 'acid vial', 'vial of acid'],
    splash: { damage: '2d6', damageType: 'acid' },
  },
  alchemists_fire: {
    // SRD thrown splash weapon — 1d4 fire on a hit, then the target burns (1d4
    // fire at the start of each of its turns; DC 10 DEX to douse).
    id: 'alchemists_fire',
    value: 50,
    name: "Alchemist's Fire (flask)",
    desc: 'A sticky, volatile fluid. Throw it (ranged attack) for 1d4 fire on a hit; the target then burns for 1d4 fire each turn until it douses the flames (DC 10 DEX).',
    weight: 1,
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ["alchemist's fire", 'alchemists fire', 'alchemist fire'],
    splash: { damage: '1d4', damageType: 'fire', burn: '1d4' },
  },
  holy_water: {
    // SRD thrown splash weapon — 2d6 radiant, but ONLY to Fiends and Undead
    // (gated on Enemy.creatureType). Splashes harmlessly off anything else.
    id: 'holy_water',
    value: 25,
    name: 'Holy Water (flask)',
    desc: 'Blessed water. Throw it (ranged attack) at a Fiend or Undead for 2d6 radiant damage on a hit; harmless to other creatures.',
    weight: 1,
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['holy water', 'flask of holy water'],
    splash: { damage: '2d6', damageType: 'radiant', vsCreatureTypes: ['undead', 'fiend'] },
  },

  // ─── Tools ───────────────────────────────────────────────────────────────────
  // Physical tools. The mechanical edge is tool *proficiency* (a Character
  // trait granted by background/class — e.g. Thieves' Tools proficiency adds the
  // proficiency bonus to a trap-disarm check); these items represent the kit
  // itself so campaigns can grant, sell, or loot them.
  thieves_tools: {
    id: 'thieves_tools',
    value: 25,
    name: "Thieves' Tools",
    desc: 'Picks, a file, and small mirrors. Proficiency lets you pick locks and disarm traps.',
    weight: 1,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    useNarrative: 'You ready your thieves’ tools — picks and probes at hand.',
    aliases: ['thieves tools', "thieves' tools", 'lockpicks', 'lock picks'],
  },
  herbalism_kit: {
    id: 'herbalism_kit',
    value: 5,
    name: 'Herbalism Kit',
    desc: 'Pouches, clippers, and vials for identifying plants and brewing remedies.',
    weight: 3,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['herbalism kit', 'herbalist kit'],
  },
  disguise_kit: {
    id: 'disguise_kit',
    value: 25,
    name: 'Disguise Kit',
    desc: 'Cosmetics, props, and prosthetics for altering your appearance.',
    weight: 3,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['disguise kit'],
  },
  forgery_kit: {
    id: 'forgery_kit',
    value: 15,
    name: 'Forgery Kit',
    desc: 'Papers, inks, seals, and wax for producing convincing fake documents.',
    weight: 5,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['forgery kit'],
  },
  navigators_tools: {
    id: 'navigators_tools',
    value: 25,
    name: "Navigator's Tools",
    desc: 'Charts, a compass, and instruments for plotting a course and avoiding hazards.',
    weight: 2,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['navigators tools', "navigator's tools"],
  },
  poisoners_kit: {
    id: 'poisoners_kit',
    value: 50,
    name: "Poisoner's Kit",
    desc: 'Vials, chemicals, and gloves for crafting and applying poisons.',
    weight: 2,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['poisoners kit', "poisoner's kit"],
  },
  artisans_tools: {
    id: 'artisans_tools',
    value: 20,
    name: "Artisan's Tools",
    desc: "A tradesperson's implements (smith's, carpenter's, mason's, etc.) for crafting goods.",
    weight: 5,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['artisans tools', "artisan's tools", 'craftsman tools'],
  },
  gaming_set: {
    id: 'gaming_set',
    value: 1,
    name: 'Gaming Set',
    desc: 'Dice or cards for a game of chance — and the social leverage a friendly wager brings.',
    weight: 0,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['gaming set', 'dice set', 'playing cards'],
  },
  musical_instrument: {
    id: 'musical_instrument',
    value: 20,
    name: 'Musical Instrument',
    desc: 'A lute, flute, drum, or horn — a Bard’s focus and a fine way to earn coin.',
    weight: 2,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['musical instrument', 'instrument', 'lute', 'flute'],
  },

  // ─── Adventuring gear ────────────────────────────────────────────────────────
  backpack: {
    id: 'backpack',
    value: 2,
    name: 'Backpack',
    desc: 'A sturdy pack for hauling your gear.',
    weight: 5,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['backpack', 'pack', 'rucksack'],
  },
  bedroll: {
    id: 'bedroll',
    value: 1,
    name: 'Bedroll',
    desc: 'A padded roll for sleeping rough on the road.',
    weight: 7,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['bedroll', 'sleeping roll'],
  },
  rope_hempen: {
    id: 'rope_hempen',
    value: 1,
    name: 'Hempen Rope (50 ft)',
    desc: '50 feet of hempen rope. Climbing, binding, and a hundred other uses.',
    weight: 10,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['rope', 'hempen rope', 'rope (50 ft)'],
  },
  grappling_hook: {
    id: 'grappling_hook',
    value: 2,
    name: 'Grappling Hook',
    desc: 'An iron hook for anchoring a rope to a ledge or wall.',
    weight: 4,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['grappling hook', 'hook'],
  },
  climbers_kit: {
    id: 'climbers_kit',
    value: 25,
    name: "Climber's Kit",
    desc: 'Pitons, boot tips, gloves, and a harness for scaling sheer surfaces.',
    weight: 12,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['climbers kit', "climber's kit"],
  },
  crowbar: {
    id: 'crowbar',
    value: 2,
    name: 'Crowbar',
    desc: 'An iron bar for prying open doors, crates, and lids.',
    weight: 5,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['crowbar', 'pry bar'],
  },
  tinderbox: {
    id: 'tinderbox',
    value: 1,
    name: 'Tinderbox',
    desc: 'Flint, steel, and tinder for starting a fire — or lighting a torch or lantern.',
    weight: 1,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['tinderbox', 'tinder box', 'flint and steel'],
  },
  waterskin: {
    id: 'waterskin',
    value: 1,
    name: 'Waterskin',
    desc: 'A leather skin holding about a day of water.',
    weight: 5,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['waterskin', 'water skin'],
  },
  mess_kit: {
    id: 'mess_kit',
    value: 1,
    name: 'Mess Kit',
    desc: 'A tin cup, cutlery, and a pan that nest together for eating on the trail.',
    weight: 1,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['mess kit'],
  },

  // ─── Ammunition ──────────────────────────────────────────────────────────────
  // Stackable bundles (default 20) equipped into the `quiver` slot. A ranged
  // attack with a matching weapon spends one (preattack.ts); when the stack hits
  // 0 it's removed and the quiver slot cleared. Each id contains the substring
  // the weapon→ammo map keys on (arrow / bolt / sling_bullet / needle /
  // firearm_bullet) so the right ammo is matched to the right weapon.
  arrows: {
    id: 'arrows',
    value: 1,
    name: 'Arrows',
    desc: 'A bundle of arrows for a shortbow or longbow.',
    weight: 1,
    type: 'misc',
    slot: 'quiver',
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['arrows', 'arrow', 'quiver of arrows'],
    count: 20,
  },
  crossbow_bolts: {
    id: 'crossbow_bolts',
    value: 1,
    name: 'Crossbow Bolts',
    desc: 'A case of bolts for a hand, light, or heavy crossbow.',
    weight: 1,
    type: 'misc',
    slot: 'quiver',
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['crossbow bolts', 'bolts', 'bolt', 'case of bolts'],
    count: 20,
  },
  sling_bullets: {
    id: 'sling_bullets',
    value: 1,
    name: 'Sling Bullets',
    desc: 'A pouch of lead bullets for a sling.',
    weight: 1,
    type: 'misc',
    slot: 'quiver',
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['sling bullets', 'sling bullet'],
    count: 20,
  },
  blowgun_needles: {
    id: 'blowgun_needles',
    value: 1,
    name: 'Blowgun Needles',
    desc: 'A tin of needles for a blowgun.',
    weight: 1,
    type: 'misc',
    slot: 'quiver',
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['blowgun needles', 'needles', 'needle'],
    count: 50,
  },
  firearm_bullets: {
    id: 'firearm_bullets',
    value: 3,
    name: 'Firearm Bullets',
    desc: 'A pouch of bullets for a musket or pistol.',
    weight: 2,
    type: 'misc',
    slot: 'quiver',
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['firearm bullets', 'firearm bullet', 'gun bullets'],
    count: 20,
  },
};

/** Every SRD item id, for contexts that want the full catalog. */
export const ALL_SRD_ITEM_IDS: string[] = Object.keys(SRD_ITEMS);

/**
 * Select canonical SRD items by id for a context's `lootTable`. This is how a
 * campaign limits which SRD equipment is available — it lists only the ids it
 * wants. Throws on an unknown id so a typo (or a since-removed item) fails
 * loudly at load time instead of silently dropping gear.
 */
export function srdItems(...ids: string[]): LootItem[] {
  return ids.map((id) => {
    const item = SRD_ITEMS[id];
    if (!item) {
      throw new Error(
        `srdItems: unknown SRD item id "${id}". Known ids: ${ALL_SRD_ITEM_IDS.join(', ')}`
      );
    }
    return item;
  });
}
