import type { LootItem } from '../../types.js';

// Shared SRD 5.2.1 equipment definitions.
//
// SRD weapons, armor, and adventuring gear are universal — a Longsword in
// Vale of Shadows is the same Longsword as in Whispering Pines. Pansori
// previously duplicated these definitions across every campaign context,
// which drifted (different weights / descriptions / aliases for the same
// item). This registry is the single source of truth.
//
// Contexts compose their `lootTable` from this registry plus their own
// custom items, and limit which SRD items are available by selecting ids:
//
//   lootTable: [
//     ...srdItems('dagger', 'longsword', 'chain_mail', 'shield', 'healing_potion'),
//     myCampaignRelic,                       // custom item, campaign-only
//   ]
//
// A campaign can override an SRD item by placing its own entry with the same
// id AFTER the spread (last-wins on `lootTable.find`), but the default is to
// share the canonical definition so the mechanics stay consistent.
//
// Item IDs match the SRD 5.2.1 names. Mechanical fields (damage, mastery,
// armor class, etc.) follow RAW (Battleaxe = Topple, per the SRD weapon table).
export const SRD_ITEMS: Record<string, LootItem> = {
  // ─── Simple melee weapons ──────────────────────────────────────────────────
  dagger: {
    id: 'dagger',
    name: 'Dagger',
    desc: '1d4 piercing, finesse, light, thrown',
    weight: 5,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    finesse: true,
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['dagger', 'knife'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'nick',
  },
  handaxe: {
    id: 'handaxe',
    name: 'Handaxe',
    desc: '1d6 slashing, light, thrown',
    weight: 5,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['handaxe', 'hand axe', 'hatchet'],
    weaponType: 'simple',
    damageType: 'slashing',
    mastery: 'vex',
  },
  quarterstaff: {
    id: 'quarterstaff',
    name: 'Quarterstaff',
    desc: '1d6 bludgeoning one-handed (1d8 two-handed)',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    versatileDamage: '1d8',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['quarterstaff', 'staff', 'quarter staff'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'topple',
  },
  mace: {
    id: 'mace',
    name: 'Mace',
    desc: '1d6 bludgeoning',
    weight: 8,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['mace'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'sap',
  },
  spear: {
    id: 'spear',
    name: 'Spear',
    desc: '1d6 piercing one-handed (1d8 two-handed), thrown 20/60',
    weight: 3,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    versatileDamage: '1d8',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['spear'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'sap',
    thrown: { normalRange: 20, longRange: 60 },
  },
  dart: {
    id: 'dart',
    name: 'Dart',
    desc: '1d4 piercing, finesse, thrown',
    weight: 1,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    finesse: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['dart', 'darts'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'vex',
  },

  club: {
    id: 'club',
    name: 'Club',
    desc: '1d4 bludgeoning, light',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['club', 'cudgel'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'slow',
  },
  greatclub: {
    id: 'greatclub',
    name: 'Greatclub',
    desc: '1d8 bludgeoning, two-handed',
    weight: 10,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['greatclub', 'great club'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'push',
  },
  javelin: {
    id: 'javelin',
    name: 'Javelin',
    desc: '1d6 piercing, thrown 30/120',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['javelin'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'slow',
    thrown: { normalRange: 30, longRange: 120 },
  },
  light_hammer: {
    id: 'light_hammer',
    name: 'Light Hammer',
    desc: '1d4 bludgeoning, light, thrown 20/60',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['light hammer', 'light_hammer', 'throwing hammer'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'nick',
    thrown: { normalRange: 20, longRange: 60 },
  },
  sickle: {
    id: 'sickle',
    name: 'Sickle',
    desc: '1d4 slashing, light',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['sickle'],
    weaponType: 'simple',
    damageType: 'slashing',
    mastery: 'nick',
  },

  // ─── Simple ranged weapons ─────────────────────────────────────────────────
  shortbow: {
    id: 'shortbow',
    name: 'Shortbow',
    desc: '1d6 piercing, ranged (80/320)',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['shortbow', 'short bow'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'vex',
  },
  light_crossbow: {
    id: 'light_crossbow',
    name: 'Light Crossbow',
    desc: '1d8 piercing, ranged (80/320), loading, two-handed',
    weight: 5,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['light crossbow', 'crossbow', 'light_crossbow'],
    weaponType: 'simple',
    damageType: 'piercing',
    mastery: 'slow',
    loading: true,
  },

  sling: {
    id: 'sling',
    name: 'Sling',
    desc: '1d4 bludgeoning, ranged (30/120)',
    weight: 1,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['sling'],
    weaponType: 'simple',
    damageType: 'bludgeoning',
    mastery: 'slow',
  },

  // ─── Martial melee weapons ─────────────────────────────────────────────────
  shortsword: {
    id: 'shortsword',
    name: 'Shortsword',
    desc: '1d6 piercing, finesse, light',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    finesse: true,
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['shortsword', 'short sword'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'vex',
  },
  rapier: {
    id: 'rapier',
    name: 'Rapier',
    desc: '1d8 piercing, finesse',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    finesse: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['rapier'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'vex',
  },
  longsword: {
    id: 'longsword',
    name: 'Longsword',
    desc: '1d8 slashing (1d10 two-handed), versatile',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    versatileDamage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['longsword', 'long sword', 'sword'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'sap',
  },
  greatsword: {
    id: 'greatsword',
    name: 'Greatsword',
    desc: '2d6 slashing, heavy, two-handed',
    weight: 10,
    type: 'weapon',
    slot: 'weapon',
    damage: '2d6',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['greatsword', 'great sword'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'graze',
    heavy: true,
  },
  battleaxe: {
    id: 'battleaxe',
    name: 'Battleaxe',
    desc: '1d8 slashing (1d10 two-handed), versatile, Topple mastery',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    versatileDamage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['battleaxe', 'battle axe', 'axe'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'topple',
  },
  greataxe: {
    id: 'greataxe',
    name: 'Greataxe',
    desc: '1d12 slashing, heavy, two-handed, Cleave mastery',
    weight: 7,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d12',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['greataxe', 'great axe'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'cleave',
    heavy: true,
  },
  glaive: {
    id: 'glaive',
    name: 'Glaive',
    desc: '1d10 slashing, heavy, two-handed, reach (10 ft)',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['glaive'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'graze',
    heavy: true,
    reach: true,
  },
  halberd: {
    id: 'halberd',
    name: 'Halberd',
    desc: '1d10 slashing, heavy, two-handed, reach (10 ft), Cleave mastery',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['halberd'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'cleave',
    heavy: true,
    reach: true,
  },
  pike: {
    id: 'pike',
    name: 'Pike',
    desc: '1d10 piercing, heavy, two-handed, reach (10 ft)',
    weight: 18,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['pike'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'push',
    heavy: true,
    reach: true,
  },
  warhammer: {
    id: 'warhammer',
    name: 'Warhammer',
    desc: '1d8 bludgeoning (1d10 two-handed), versatile',
    weight: 5,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    versatileDamage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['warhammer', 'hammer'],
    weaponType: 'martial',
    damageType: 'bludgeoning',
    mastery: 'push',
  },

  flail: {
    id: 'flail',
    name: 'Flail',
    desc: '1d8 bludgeoning',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['flail'],
    weaponType: 'martial',
    damageType: 'bludgeoning',
    mastery: 'sap',
  },
  lance: {
    id: 'lance',
    name: 'Lance',
    desc: '1d10 piercing, heavy, reach (10 ft), two-handed unless mounted',
    weight: 6,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['lance'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'topple',
    heavy: true,
    reach: true,
  },
  maul: {
    id: 'maul',
    name: 'Maul',
    desc: '2d6 bludgeoning, heavy, two-handed',
    weight: 10,
    type: 'weapon',
    slot: 'weapon',
    damage: '2d6',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['maul'],
    weaponType: 'martial',
    damageType: 'bludgeoning',
    mastery: 'topple',
    heavy: true,
  },
  morningstar: {
    id: 'morningstar',
    name: 'Morningstar',
    desc: '1d8 piercing',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['morningstar', 'morning star'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'sap',
  },
  scimitar: {
    id: 'scimitar',
    name: 'Scimitar',
    desc: '1d6 slashing, finesse, light',
    weight: 3,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    finesse: true,
    light: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['scimitar'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'nick',
  },
  trident: {
    id: 'trident',
    name: 'Trident',
    desc: '1d8 piercing (1d10 two-handed), versatile, thrown 20/60',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    versatileDamage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['trident'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'topple',
    thrown: { normalRange: 20, longRange: 60 },
  },
  war_pick: {
    id: 'war_pick',
    name: 'War Pick',
    desc: '1d8 piercing (1d10 two-handed), versatile',
    weight: 2,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    versatileDamage: '1d10',
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['war pick', 'war_pick', 'warpick'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'sap',
  },
  whip: {
    id: 'whip',
    name: 'Whip',
    desc: '1d4 slashing, finesse, reach (10 ft)',
    weight: 3,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d4',
    finesse: true,
    range: 'melee',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['whip'],
    weaponType: 'martial',
    damageType: 'slashing',
    mastery: 'slow',
    reach: true,
  },

  // ─── Martial ranged weapons ────────────────────────────────────────────────
  longbow: {
    id: 'longbow',
    name: 'Longbow',
    desc: '1d8 piercing, heavy, ranged (150/600)',
    weight: 4,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d8',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['longbow', 'long bow'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'slow',
    heavy: true,
  },
  hand_crossbow: {
    id: 'hand_crossbow',
    name: 'Hand Crossbow',
    desc: '1d6 piercing, light, ranged (30/120), loading',
    weight: 3,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d6',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['hand crossbow', 'hand_crossbow', 'crossbow_hand'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'vex',
    light: true,
    loading: true,
  },
  heavy_crossbow: {
    id: 'heavy_crossbow',
    name: 'Heavy Crossbow',
    desc: '1d10 piercing, heavy, ranged (100/400), loading, two-handed',
    weight: 18,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['heavy crossbow', 'heavy_crossbow'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'push',
    heavy: true,
    loading: true,
  },

  blowgun: {
    id: 'blowgun',
    name: 'Blowgun',
    desc: '1 piercing, ranged (25/100), loading',
    weight: 1,
    type: 'weapon',
    slot: 'weapon',
    damage: '1',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['blowgun', 'blow gun'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'vex',
    loading: true,
  },
  musket: {
    id: 'musket',
    name: 'Musket',
    desc: '1d12 piercing, ranged (40/120), loading, two-handed',
    weight: 10,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d12',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['musket'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'slow',
    loading: true,
  },
  pistol: {
    id: 'pistol',
    name: 'Pistol',
    desc: '1d10 piercing, ranged (30/90), loading',
    weight: 3,
    type: 'weapon',
    slot: 'weapon',
    damage: '1d10',
    range: 'ranged',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['pistol', 'flintlock'],
    weaponType: 'martial',
    damageType: 'piercing',
    mastery: 'vex',
    loading: true,
  },

  // ─── Armor ─────────────────────────────────────────────────────────────────
  padded_armor: {
    id: 'padded_armor',
    name: 'Padded Armor',
    desc: 'AC 11 + DEX modifier, light armor (stealth disadvantage)',
    weight: 8,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 11,
    armorCategory: 'light',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['padded armor', 'padded'],
  },
  leather_armor: {
    id: 'leather_armor',
    name: 'Leather Armor',
    desc: 'AC 11 + DEX modifier, light armor',
    weight: 10,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 11,
    armorCategory: 'light',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['leather armor', 'leather'],
  },
  studded_leather: {
    id: 'studded_leather',
    name: 'Studded Leather',
    desc: 'AC 12 + DEX modifier, light armor',
    weight: 13,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 12,
    armorCategory: 'light',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['studded leather', 'studded'],
  },
  chain_shirt: {
    id: 'chain_shirt',
    name: 'Chain Shirt',
    desc: 'AC 13 + DEX (max +2), medium armor',
    weight: 20,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 13,
    dexCapToAc: 2,
    armorCategory: 'medium',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['chain shirt'],
  },
  scale_mail: {
    id: 'scale_mail',
    name: 'Scale Mail',
    desc: 'AC 14 + DEX (max +2), medium armor',
    weight: 6,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 14,
    dexCapToAc: 2,
    armorCategory: 'medium',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['scale mail', 'scale', 'scalemail'],
  },
  hide_armor: {
    id: 'hide_armor',
    name: 'Hide Armor',
    desc: 'AC 12 + DEX (max +2), medium armor',
    weight: 12,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 12,
    dexCapToAc: 2,
    armorCategory: 'medium',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['hide armor', 'hide'],
  },
  breastplate: {
    id: 'breastplate',
    name: 'Breastplate',
    desc: 'AC 14 + DEX (max +2), medium armor',
    weight: 20,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 14,
    dexCapToAc: 2,
    armorCategory: 'medium',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['breastplate', 'breast plate'],
  },
  half_plate: {
    id: 'half_plate',
    name: 'Half Plate Armor',
    desc: 'AC 15 + DEX (max +2), medium armor (stealth disadvantage)',
    weight: 40,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 15,
    dexCapToAc: 2,
    armorCategory: 'medium',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['half plate', 'half_plate', 'half plate armor'],
  },
  chain_mail: {
    id: 'chain_mail',
    name: 'Chain Mail',
    desc: 'AC 16, heavy armor (STR 13 required)',
    weight: 55,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 16,
    dexCapToAc: 0,
    armorCategory: 'heavy',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['chain mail', 'chainmail'],
  },
  plate_armor: {
    id: 'plate_armor',
    name: 'Plate Armor',
    desc: 'AC 18, heavy armor (STR 15 required)',
    weight: 65,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 18,
    dexCapToAc: 0,
    armorCategory: 'heavy',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['plate armor', 'plate'],
  },
  ring_mail: {
    id: 'ring_mail',
    name: 'Ring Mail',
    desc: 'AC 14, heavy armor (stealth disadvantage)',
    weight: 40,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 14,
    dexCapToAc: 0,
    armorCategory: 'heavy',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['ring mail', 'ringmail'],
  },
  splint_armor: {
    id: 'splint_armor',
    name: 'Splint Armor',
    desc: 'AC 17, heavy armor (STR 15 required, stealth disadvantage)',
    weight: 60,
    type: 'armor',
    slot: 'armor',
    damage: null,
    armorAcBase: 17,
    dexCapToAc: 0,
    armorCategory: 'heavy',
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['splint', 'splint armor', 'splint mail'],
  },
  shield: {
    id: 'shield',
    name: 'Shield',
    desc: '+2 AC while equipped',
    weight: 12,
    type: 'armor',
    slot: 'shield',
    damage: null,
    armorCategory: 'shield',
    ac_bonus: 2,
    heal: null,
    effect: null,
    aliases: ['shield'],
  },

  // ─── Adventuring gear / consumables ─────────────────────────────────────────
  healing_potion: {
    id: 'healing_potion',
    name: 'Healing Potion',
    desc: 'Restores 2d4+2 HP when consumed.',
    weight: 2,
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: '2d4+2',
    effect: null,
    aliases: ['healing potion', 'potion', 'health potion'],
  },
  healers_kit: {
    // Healer's Kit (SRD) — 10 uses. The Healer feat lets a PC use a
    // charge to heal a creature with the Use-an-Object action. Charges tracked
    // via inventory `count`; the `use_healer_kit` handler decrements.
    id: 'healers_kit',
    name: "Healer's Kit",
    desc: 'Bag of bandages, splints, and salves. 10 uses. With the Healer feat, an action heals 1d6 + 4 + prof bonus HP per use.',
    weight: 3,
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['healers kit', "healer's kit", 'healers_kit'],
  },
  holy_symbol: {
    id: 'holy_symbol',
    name: 'Holy Symbol',
    desc: 'A holy symbol that serves as a divine spellcasting focus.',
    weight: 2,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: 'spellcasting_focus',
    aliases: ['holy symbol', 'symbol', 'holy focus'],
  },
  component_pouch: {
    id: 'component_pouch',
    name: 'Component Pouch',
    desc: 'A leather pouch of spellcasting components.',
    weight: 2,
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: 'spellcasting_focus',
    aliases: ['component pouch', 'pouch', 'spell components'],
  },
};

/** Every SRD item id, for contexts that want the full catalog. */
export const ALL_SRD_ITEM_IDS: string[] = Object.keys(SRD_ITEMS);

/**
 * Select canonical SRD items by id for a context's `lootTable`. This is how a
 * campaign limits which SRD equipment is available — it lists only the ids it
 * wants. Throws on an unknown id so a typo (or a since-removed item) fails
 * loudly at load time instead of silently dropping gear.
 */
export function srdItems(...ids: string[]): LootItem[] {
  return ids.map((id) => {
    const item = SRD_ITEMS[id];
    if (!item) {
      throw new Error(
        `srdItems: unknown SRD item id "${id}". Known ids: ${ALL_SRD_ITEM_IDS.join(', ')}`
      );
    }
    return item;
  });
}
