import type { EnemyTemplate } from '../../types.js';

// Shared SRD bestiary entries.
//
// 5e bestiary stat blocks are universal — a Goblin in Vale of Shadows is the
// same Goblin in Whispering Pines. Pansori previously duplicated these
// definitions across every campaign context; this registry is the single
// source of truth.
//
// Contexts spread an entry and override what's themed for the campaign:
//
//   enemyTemplates: [
//     { ...SRD_MONSTERS.skeleton, name: 'Skeleton Warrior', resistances: ['piercing'] },
//     { ...SRD_MONSTERS.wolf, name: 'Frost Wolf', resistances: ['cold'] },
//   ],
//
// Bosses and campaign-unique creatures (Crypt Lord, Frost Acolyte, Fey
// Trickster, Frost Cultist, etc.) stay inline in their context — they aren't
// SRD baseline and don't generalize across campaigns.
//
// Stat blocks follow SRD 5.2.1 where available. Numeric stats match the
// printed monster manual entries; campaigns add cosmetic deltas
// (name/damageType/resistances) without re-stating the math.

// Helper type — the `name` field gets overridden by every campaign anyway,
// so the base entries supply a default name that callers can replace.
type SrdMonster = EnemyTemplate;

export const SRD_MONSTERS: Record<string, SrdMonster> = {
  // ─── CR 1/8 ────────────────────────────────────────────────────────────────
  bandit: {
    name: 'Bandit',
    darkvision_ft: 0, // human — no darkvision
    cr: 0.125,
    hp: 11,
    ac: 12,
    damage: '1d6+1',
    toHit: 3,
    xp: 25,
    str: 11,
    dex: 12,
    con: 12,
    int: 10,
    wis: 10,
    cha: 10,
    damageType: 'slashing',
  },

  // ─── CR 1/4 ────────────────────────────────────────────────────────────────
  goblin: {
    name: 'Goblin',
    cr: 0.25,
    hp: 7,
    ac: 15,
    damage: '1d6+2',
    toHit: 4,
    xp: 50,
    str: 8,
    dex: 14,
    con: 10,
    int: 10,
    wis: 8,
    cha: 8,
  },
  skeleton: {
    name: 'Skeleton',
    cr: 0.25,
    hp: 13,
    ac: 13,
    damage: '1d6+2',
    toHit: 4,
    xp: 50,
    str: 10,
    dex: 14,
    con: 15,
    int: 6,
    wis: 8,
    cha: 5,
    vulnerabilities: ['bludgeoning'],
    immunities: ['poison'],
    condition_immunities: ['poisoned', 'exhaustion'],
  },
  wolf: {
    name: 'Wolf',
    cr: 0.25,
    hp: 11,
    ac: 13,
    damage: '1d6+1',
    toHit: 4,
    xp: 50,
    str: 12,
    dex: 15,
    con: 12,
    int: 3,
    wis: 12,
    cha: 6,
    packTactics: true,
    damageType: 'piercing',
  },
  giant_spider: {
    name: 'Giant Spider',
    cr: 0.25,
    hp: 13,
    ac: 14,
    damage: '1d8',
    toHit: 5,
    xp: 100,
    str: 8,
    dex: 16,
    con: 11,
    int: 2,
    wis: 11,
    cha: 4,
    onHitEffect: { condition: 'poisoned', ability: 'con', dc: 11 },
    damageType: 'piercing',
  },

  // ─── CR 1/2 ────────────────────────────────────────────────────────────────
  orc: {
    name: 'Orc',
    cr: 0.5,
    hp: 15,
    ac: 13,
    damage: '1d12+3',
    toHit: 5,
    xp: 100,
    str: 16,
    dex: 12,
    con: 16,
    int: 7,
    wis: 11,
    cha: 10,
  },
  shadow: {
    name: 'Shadow',
    cr: 0.5,
    hp: 16,
    ac: 12,
    damage: '2d6+2',
    toHit: 4,
    xp: 100,
    str: 6,
    dex: 14,
    con: 13,
    int: 6,
    wis: 10,
    cha: 8,
    resistances: [
      'acid',
      'fire',
      'thunder',
      'lightning',
      'cold',
      'bludgeoning',
      'piercing',
      'slashing',
    ],
    immunities: ['necrotic', 'poison'],
    condition_immunities: [
      'exhaustion',
      'frightened',
      'grappled',
      'paralyzed',
      'petrified',
      'poisoned',
      'prone',
      'restrained',
    ],
    damageType: 'necrotic',
  },
  ice_mephit: {
    name: 'Ice Mephit',
    cr: 0.5,
    hp: 21,
    ac: 11,
    damage: '1d4+2',
    toHit: 4,
    xp: 100,
    str: 7,
    dex: 13,
    con: 10,
    int: 9,
    wis: 11,
    cha: 12,
    immunities: ['cold'],
    vulnerabilities: ['fire'],
    condition_immunities: ['poisoned'],
    damageType: 'cold',
  },

  // ─── CR 1 ──────────────────────────────────────────────────────────────────
  ghoul: {
    name: 'Ghoul',
    cr: 1,
    hp: 22,
    ac: 13,
    damage: '2d6+2',
    toHit: 4,
    xp: 200,
    str: 13,
    dex: 15,
    con: 10,
    int: 7,
    wis: 10,
    cha: 6,
    onHitEffect: { condition: 'paralyzed', ability: 'con', dc: 10 },
    condition_immunities: ['poisoned', 'charmed'],
    damageType: 'piercing',
  },
  brown_bear: {
    name: 'Brown Bear',
    cr: 1,
    hp: 34,
    ac: 11,
    damage: '2d6+4',
    toHit: 5,
    xp: 200,
    str: 19,
    dex: 10,
    con: 16,
    int: 2,
    wis: 13,
    cha: 7,
    multiattack: 2,
    damageType: 'slashing',
  },

  // ─── CR 2 ──────────────────────────────────────────────────────────────────
  cult_fanatic: {
    name: 'Cult Fanatic',
    darkvision_ft: 0, // human — no darkvision
    cr: 2,
    hp: 33,
    ac: 13,
    damage: '1d4+2',
    toHit: 4,
    xp: 450,
    str: 9,
    dex: 14,
    con: 11,
    int: 12,
    wis: 14,
    cha: 14,
    onHitEffect: { condition: 'poisoned', ability: 'con', dc: 13 },
  },
  ogre: {
    name: 'Ogre',
    cr: 2,
    hp: 59,
    ac: 11,
    damage: '2d8+4',
    toHit: 6,
    xp: 450,
    str: 19,
    dex: 8,
    con: 16,
    int: 5,
    wis: 7,
    cha: 7,
    multiattack: 2,
  },

  // ─── More CR 1/8 ─────────────────────────────────────────────────────────────
  // Pack Tactics / Sunlight Sensitivity (Kobold, Giant Rat) deferred — no
  // ally-adjacency advantage / lighting model yet.
  kobold: {
    name: 'Kobold',
    cr: 0.125,
    hp: 7,
    ac: 14,
    damage: '1d4+2',
    toHit: 4,
    xp: 25,
    str: 7,
    dex: 15,
    con: 9,
    int: 8,
    wis: 7,
    cha: 8,
    packTactics: true,
    damageType: 'piercing',
    sunlightSensitivity: true,
  },
  guard: {
    name: 'Guard',
    darkvision_ft: 0, // human — no darkvision
    cr: 0.125,
    hp: 11,
    ac: 16,
    damage: '1d6+1',
    toHit: 3,
    xp: 25,
    str: 13,
    dex: 12,
    con: 12,
    int: 10,
    wis: 11,
    cha: 10,
    damageType: 'piercing',
  },
  cultist: {
    name: 'Cultist',
    darkvision_ft: 0, // human — no darkvision
    cr: 0.125,
    hp: 9,
    ac: 12,
    damage: '1d4+1',
    toHit: 3,
    xp: 25,
    str: 11,
    dex: 12,
    con: 10,
    int: 10,
    wis: 11,
    cha: 10,
    damageType: 'slashing',
    bonusDamage: '1', // Ritual Sickle: +1 Necrotic
    bonusDamageType: 'necrotic',
  },
  giant_rat: {
    name: 'Giant Rat',
    cr: 0.125,
    hp: 7,
    ac: 13,
    damage: '1d4+3',
    toHit: 5,
    xp: 25,
    str: 7,
    dex: 16,
    con: 11,
    int: 2,
    wis: 10,
    cha: 4,
    packTactics: true,
    damageType: 'piercing',
  },

  // ─── More CR 1/4 ─────────────────────────────────────────────────────────────
  zombie: {
    name: 'Zombie',
    cr: 0.25,
    hp: 15,
    ac: 8,
    damage: '1d6+1',
    toHit: 3,
    xp: 50,
    str: 13,
    dex: 6,
    con: 16,
    int: 3,
    wis: 6,
    cha: 5,
    immunities: ['poison'],
    condition_immunities: ['poisoned', 'exhaustion'],
    damageType: 'bludgeoning',
    // Undead Fortitude — a non-Radiant, non-Crit hit that would drop it to 0
    // HP lets it make a CON save (DC 5 + damage) to cling to 1 HP instead.
    undeadFortitude: true,
  },

  // ─── More CR 1/2 ─────────────────────────────────────────────────────────────
  scout: {
    name: 'Scout',
    darkvision_ft: 0, // human — no darkvision
    cr: 0.5,
    hp: 16,
    ac: 13,
    damage: '1d6+2',
    toHit: 4,
    xp: 100,
    str: 11,
    dex: 14,
    con: 12,
    int: 11,
    wis: 13,
    cha: 11,
    multiattack: 2,
    damageType: 'piercing',
  },
  worg: {
    name: 'Worg',
    cr: 0.5,
    hp: 26,
    ac: 13,
    damage: '1d8+3',
    toHit: 5,
    xp: 100,
    str: 16,
    dex: 13,
    con: 13,
    int: 7,
    wis: 11,
    cha: 8,
    speedFt: 50,
    packTactics: true,
    damageType: 'piercing',
  },
  gnoll: {
    name: 'Gnoll',
    cr: 0.5,
    hp: 27,
    ac: 15,
    damage: '1d6+2',
    toHit: 4,
    xp: 100,
    str: 14,
    dex: 12,
    con: 11,
    int: 6,
    wis: 10,
    cha: 7,
    damageType: 'piercing',
    // SRD: Rampage (1/Day) — after damaging an already-Bloodied target, move up
    // to half Speed and make one extra Rend.
    rampage: true,
  },
  black_bear: {
    name: 'Black Bear',
    cr: 0.5,
    hp: 19,
    ac: 11,
    damage: '1d6+2',
    toHit: 4,
    xp: 100,
    str: 15,
    dex: 12,
    con: 14,
    int: 2,
    wis: 12,
    cha: 7,
    multiattack: 2,
    damageType: 'slashing',
  },

  // ─── More CR 1 ───────────────────────────────────────────────────────────────
  dire_wolf: {
    name: 'Dire Wolf',
    cr: 1,
    hp: 22,
    ac: 14,
    damage: '1d8+3',
    toHit: 5,
    xp: 200,
    str: 17,
    dex: 15,
    con: 15,
    int: 3,
    wis: 12,
    cha: 7,
    speedFt: 50,
    packTactics: true,
    damageType: 'piercing',
  },
  specter: {
    name: 'Specter',
    cr: 1,
    hp: 22,
    ac: 12,
    // Life Drain — all-necrotic attack; the necrotic damage also reduces the
    // target's Hit Point maximum by that amount (see `lifeDrain` below).
    damage: '3d6',
    toHit: 4,
    xp: 200,
    str: 1,
    dex: 14,
    con: 11,
    int: 10,
    wis: 10,
    cha: 11,
    resistances: [
      'acid',
      'bludgeoning',
      'cold',
      'fire',
      'lightning',
      'piercing',
      'slashing',
      'thunder',
    ],
    immunities: ['necrotic', 'poison'],
    condition_immunities: [
      'charmed',
      'exhaustion',
      'grappled',
      'paralyzed',
      'petrified',
      'poisoned',
      'prone',
      'restrained',
      'unconscious',
    ],
    speedFt: 50, // hovering flight
    damageType: 'necrotic',
    lifeDrain: true,
    sunlightSensitivity: true,
  },
  animated_armor: {
    name: 'Animated Armor',
    cr: 1,
    hp: 33,
    ac: 18,
    damage: '1d6+2',
    toHit: 4,
    xp: 200,
    str: 14,
    dex: 11,
    con: 13,
    int: 1,
    wis: 3,
    cha: 1,
    multiattack: 2,
    immunities: ['poison', 'psychic'],
    condition_immunities: [
      'charmed',
      'deafened',
      'exhaustion',
      'frightened',
      'paralyzed',
      'petrified',
      'poisoned',
    ],
    speedFt: 25,
    damageType: 'bludgeoning',
  },

  // ─── More CR 2 ───────────────────────────────────────────────────────────────
  bandit_captain: {
    name: 'Bandit Captain',
    darkvision_ft: 0, // human — no darkvision
    cr: 2,
    hp: 52,
    ac: 15,
    damage: '1d6+3',
    toHit: 5,
    xp: 450,
    str: 15,
    dex: 16,
    con: 14,
    int: 14,
    wis: 11,
    cha: 14,
    multiattack: 2,
    damageType: 'slashing',
    // SRD: Parry — reaction, +2 AC vs one melee attack that hits while armed.
    parry: true,
  },
  berserker: {
    name: 'Berserker',
    darkvision_ft: 0, // human — no darkvision
    cr: 2,
    hp: 67,
    ac: 13,
    damage: '1d12+3',
    toHit: 5,
    xp: 450,
    str: 16,
    dex: 12,
    con: 17,
    int: 9,
    wis: 11,
    cha: 9,
    bloodiedFrenzy: true,
    damageType: 'slashing',
  },
  ghast: {
    name: 'Ghast',
    cr: 2,
    hp: 36,
    ac: 13,
    damage: '2d6+3',
    toHit: 5,
    xp: 450,
    str: 16,
    dex: 17,
    con: 10,
    int: 11,
    wis: 10,
    cha: 8,
    onHitEffect: { condition: 'paralyzed', ability: 'con', dc: 10 },
    resistances: ['necrotic'],
    immunities: ['poison'],
    condition_immunities: ['charmed', 'exhaustion', 'poisoned'],
    damageType: 'slashing',
    bonusDamage: '2d8', // claw rider ≈ the bite's necrotic
    bonusDamageType: 'necrotic',
    // Stench — a creature that starts its turn within 5 ft makes a CON save
    // (DC 10) or is Poisoned until the start of its next turn. (The RAW
    // 24-hour immunity on a success is not tracked — the target re-saves
    // each turn it begins in the emanation.)
    aura: {
      radiusFt: 5,
      save: { ability: 'con', dc: 10 },
      condition: 'poisoned',
      conditionDuration: 1,
      name: 'Stench',
    },
  },
  griffon: {
    name: 'Griffon',
    cr: 2,
    hp: 59,
    ac: 12,
    damage: '1d8+4',
    toHit: 6,
    xp: 450,
    str: 18,
    dex: 15,
    con: 16,
    int: 2,
    wis: 13,
    cha: 8,
    multiattack: 2,
    speedFt: 80, // flight
    damageType: 'piercing',
    // SRD: Griffon — Rend grapples a Medium-or-smaller target on a hit (no save,
    // escape DC 14) from both front claws. All PCs are Medium/Small, so the
    // size gate always allows it. Auto-apply onHitEffect (omitted save).
    onHitEffect: { condition: 'grappled', escapeDc: 14 },
  },

  // ─── More CR 3 ───────────────────────────────────────────────────────────────
  owlbear: {
    name: 'Owlbear',
    cr: 3,
    hp: 59,
    ac: 13,
    damage: '2d8+5',
    toHit: 7,
    xp: 700,
    str: 20,
    dex: 12,
    con: 17,
    int: 3,
    wis: 12,
    cha: 7,
    multiattack: 2,
    speedFt: 40,
    damageType: 'slashing',
  },
  manticore: {
    name: 'Manticore',
    cr: 3,
    hp: 68,
    ac: 14,
    damage: '1d8+3',
    toHit: 5,
    xp: 700,
    str: 17,
    dex: 16,
    con: 17,
    int: 7,
    wis: 12,
    cha: 8,
    multiattack: 3, // Rend / Tail Spike in any combination
    damageType: 'slashing',
  },
  wight: {
    name: 'Wight',
    cr: 3,
    hp: 82,
    ac: 14,
    damage: '1d8+2',
    toHit: 4,
    xp: 700,
    str: 15,
    dex: 14,
    con: 16,
    int: 10,
    wis: 13,
    cha: 15,
    multiattack: 2,
    resistances: ['necrotic'],
    immunities: ['poison'],
    condition_immunities: ['exhaustion', 'poisoned'],
    damageType: 'slashing',
    bonusDamage: '1d8', // Necrotic Sword rider
    bonusDamageType: 'necrotic',
    // Life Drain — the necrotic portion of the hit also reduces the target's
    // Hit Point maximum by that amount.
    lifeDrain: true,
    sunlightSensitivity: true,
  },

  // ─── More SRD bestiary (CR 1–5) ──────────────────────────────────────────────
  // Fliers, big beasts, a second grapple-on-hit, a full undead kit, and the
  // first CR 5 brute. All use already-supported fields; per-monster special
  // actions are noted as deferred where the engine can't yet express them.
  hippogriff: {
    name: 'Hippogriff',
    darkvision_ft: 0, // relies on sight — no darkvision
    cr: 1,
    hp: 26,
    ac: 11,
    damage: '1d8+3',
    toHit: 5,
    xp: 200,
    str: 17,
    dex: 13,
    con: 13,
    int: 2,
    wis: 12,
    cha: 8,
    multiattack: 2,
    speedFt: 60, // flight
    damageType: 'slashing',
    // SRD: Flyby (no OA when flying out of reach) deferred — no fly-OA model.
  },
  giant_eagle: {
    name: 'Giant Eagle',
    darkvision_ft: 0, // relies on sight — no darkvision
    cr: 1,
    hp: 26,
    ac: 13,
    damage: '1d4+3',
    toHit: 5,
    xp: 200,
    str: 16,
    dex: 17,
    con: 13,
    int: 8,
    wis: 14,
    cha: 10,
    multiattack: 2,
    speedFt: 80, // flight
    damageType: 'slashing',
    // SRD: Rend deals +1d6 Radiant; halved only if the target resists radiant.
    bonusDamage: '1d6',
    bonusDamageType: 'radiant',
    resistances: ['necrotic', 'radiant'],
  },
  lion: {
    name: 'Lion',
    cr: 1,
    hp: 22,
    ac: 12,
    damage: '1d8+3',
    toHit: 5,
    xp: 200,
    str: 17,
    dex: 15,
    con: 11,
    int: 3,
    wis: 12,
    cha: 8,
    multiattack: 2,
    speedFt: 50,
    damageType: 'slashing',
    // SRD: Pack Tactics — Advantage when an ally is within 5 ft of the target.
    packTactics: true,
    // SRD: Roar (WIS save → Frightened) deferred — modeled as a plain attacker.
  },
  bugbear_warrior: {
    name: 'Bugbear Warrior',
    cr: 1,
    hp: 33,
    ac: 14,
    damage: '2d6+2',
    toHit: 4,
    xp: 200,
    str: 15,
    dex: 14,
    con: 13,
    int: 8,
    wis: 11,
    cha: 9,
    attackReachFt: 10,
    damageType: 'bludgeoning',
    // SRD: Grab — on a hit, a Medium-or-smaller target is Grappled (escape DC
    // 12). Reuses the Griffon's auto-apply grapple-on-hit path.
    onHitEffect: { condition: 'grappled', escapeDc: 12 },
  },
  saber_toothed_tiger: {
    name: 'Saber-Toothed Tiger',
    cr: 2,
    hp: 52,
    ac: 13,
    damage: '2d6+4',
    toHit: 6,
    xp: 450,
    str: 18,
    dex: 17,
    con: 15,
    int: 3,
    wis: 12,
    cha: 8,
    multiattack: 2,
    speedFt: 40,
    damageType: 'slashing',
  },
  giant_boar: {
    name: 'Giant Boar',
    darkvision_ft: 0, // no darkvision
    cr: 2,
    hp: 42,
    ac: 13,
    damage: '2d6+3',
    toHit: 5,
    xp: 450,
    str: 17,
    dex: 10,
    con: 16,
    int: 2,
    wis: 7,
    cha: 5,
    speedFt: 40,
    damageType: 'piercing',
    // SRD: Bloodied Fury — Advantage on melee attacks while the boar is Bloodied.
    bloodiedFrenzy: true,
    // SRD: charge rider (+2d6 + Prone after moving 20+ ft) deferred.
  },
  mummy: {
    name: 'Mummy',
    cr: 3,
    hp: 58,
    ac: 11,
    damage: '1d10+3',
    toHit: 5,
    xp: 700,
    str: 16,
    dex: 8,
    con: 15,
    int: 6,
    wis: 12,
    cha: 12,
    multiattack: 2,
    speedFt: 20,
    damageType: 'bludgeoning',
    // SRD: Rotting Fist adds 3d6 Necrotic (halved if the target resists it).
    bonusDamage: '3d6',
    bonusDamageType: 'necrotic',
    vulnerabilities: ['fire'],
    immunities: ['necrotic', 'poison'],
    condition_immunities: ['charmed', 'exhaustion', 'frightened', 'paralyzed', 'poisoned'],
    // SRD: Dreadful Glare (WIS save DC 11 → Frightened) folded onto the attack as
    // an on-hit save rider. The Rotting Curse (can't regain HP + max-HP decay)
    // and turn-to-dust-at-0 are deferred — they need no-heal-curse infra.
    onHitEffect: { condition: 'frightened', ability: 'wis', dc: 11 },
  },
  hill_giant: {
    name: 'Hill Giant',
    darkvision_ft: 0, // no darkvision
    cr: 5,
    hp: 105,
    ac: 13,
    damage: '3d8+5',
    toHit: 8,
    xp: 1800,
    str: 21,
    dex: 8,
    con: 19,
    int: 5,
    wis: 9,
    cha: 6,
    multiattack: 2,
    attackReachFt: 10,
    speedFt: 40,
    damageType: 'bludgeoning',
    // SRD: Tree Club knocks a Large-or-smaller target Prone on a hit (deferred —
    // auto-prone every hit is punishing without a stand-up budget model); the
    // ranged Trash Lob (+ Poisoned) collapses to this melee profile.
  },

  // ─── High-end SRD bestiary (CR 4–6) ──────────────────────────────────────────
  ettin: {
    name: 'Ettin',
    cr: 4,
    hp: 85,
    ac: 12,
    damage: '2d8+5',
    toHit: 7,
    xp: 1100,
    str: 21,
    dex: 8,
    con: 17,
    int: 6,
    wis: 10,
    cha: 8,
    multiattack: 2, // Battleaxe + Morningstar
    speedFt: 40,
    damageType: 'slashing',
    // SRD: two heads — immune to a suite of "lose your senses/turn" conditions.
    condition_immunities: [
      'blinded',
      'charmed',
      'deafened',
      'frightened',
      'stunned',
      'unconscious',
    ],
    // SRD: Battleaxe Prone rider + Morningstar's Disadvantage rider deferred.
  },
  gladiator: {
    name: 'Gladiator',
    darkvision_ft: 0, // human — no darkvision
    cr: 5,
    hp: 112,
    ac: 16,
    damage: '2d6+4',
    toHit: 7,
    xp: 1800,
    str: 18,
    dex: 15,
    con: 16,
    int: 10,
    wis: 12,
    cha: 15,
    multiattack: 3, // three Spear attacks
    speedFt: 30,
    damageType: 'piercing',
    // SRD: Parry reaction adds +3 AC (its proficiency bonus) vs one melee hit.
    parry: true,
    parryBonus: 3,
    // SRD: Shield Bash (STR save → damage + Prone) collapses to a Spear attack.
  },
  wraith: {
    name: 'Wraith',
    cr: 5,
    hp: 67,
    ac: 13,
    damage: '4d8+3',
    toHit: 6,
    xp: 1800,
    str: 6,
    dex: 16,
    con: 16,
    int: 12,
    wis: 14,
    cha: 15,
    speedFt: 60, // fly (hover)
    damageType: 'necrotic',
    // SRD: incorporeal — resists physical + several elements, full undead suite.
    resistances: ['acid', 'bludgeoning', 'cold', 'fire', 'piercing', 'slashing'],
    immunities: ['necrotic', 'poison'],
    condition_immunities: [
      'charmed',
      'exhaustion',
      'grappled',
      'paralyzed',
      'petrified',
      'poisoned',
      'prone',
      'restrained',
      'unconscious',
    ],
    // SRD: Life Drain — the necrotic hit also lowers the target's HP maximum.
    lifeDrain: true,
    // SRD: Sunlight Sensitivity — Disadvantage on attacks while in sunlight.
    // (Create Specter deferred — a campaign-timeline mechanic.)
    sunlightSensitivity: true,
  },
  fire_elemental: {
    name: 'Fire Elemental',
    cr: 5,
    hp: 93,
    ac: 13,
    damage: '2d6+3',
    toHit: 6,
    xp: 1800,
    str: 10,
    dex: 17,
    con: 16,
    int: 6,
    wis: 10,
    cha: 7,
    multiattack: 2, // two Burn attacks
    speedFt: 50,
    damageType: 'fire',
    resistances: ['bludgeoning', 'piercing', 'slashing'],
    immunities: ['fire', 'poison'],
    condition_immunities: [
      'exhaustion',
      'grappled',
      'paralyzed',
      'petrified',
      'poisoned',
      'prone',
      'restrained',
      'unconscious',
    ],
    // SRD: Fire Aura — 10-ft emanation, 1d10 Fire. Modeled via the PC-turn-start
    // aura hook (the RAW end-of-its-turn timing is approximated, like Stench).
    aura: { radiusFt: 10, damage: '1d10', damageType: 'fire', name: 'Fire Aura' },
  },
  wyvern: {
    name: 'Wyvern',
    darkvision_ft: 120,
    cr: 6,
    hp: 127,
    ac: 14,
    damage: '2d6+4',
    toHit: 7,
    xp: 2300,
    str: 19,
    dex: 10,
    con: 16,
    int: 5,
    wis: 12,
    cha: 6,
    speedFt: 80, // fly
    attackReachFt: 10, // the Sting
    damageType: 'piercing',
    // SRD: Sting modeled as the wyvern's signature attack — +7d6 Poison and a
    // CON save vs Poisoned. (RAW the 2024 Sting auto-poisons with no save and the
    // wyvern also Bites; the bite + no-save-with-duration are deferred.)
    bonusDamage: '7d6',
    bonusDamageType: 'poison',
    onHitEffect: { condition: 'poisoned', ability: 'con', dc: 14 },
  },

  // ─── CR 7–10 tier — giants, the giant ape, and the first dragon ─────────────
  // The engine models one primary attack + a multiattack count; each giant's
  // ranged option (Boulder / Great Bow / Hammer Throw / Thundercloud) and
  // recharge/bonus-action specials (Deflect Missile, War Cry, Boulder Toss, the
  // dragon's Fire Breath, Cloud Giant Spellcasting) are deferred/narrated — the
  // melee attack is the signature, like the Wyvern's Sting.

  // SRD: Stone Giant (CR 7) — two Stone Club attacks at 15-ft reach.
  stone_giant: {
    name: 'Stone Giant',
    cr: 7,
    hp: 126,
    ac: 17,
    damage: '3d10+6',
    toHit: 9,
    xp: 2900,
    str: 23,
    dex: 15,
    con: 20,
    int: 10,
    wis: 12,
    cha: 9,
    multiattack: 2,
    speedFt: 40,
    attackReachFt: 15, // the Stone Club's long reach
    damageType: 'bludgeoning',
    darkvision_ft: 60,
  },

  // SRD: Giant Ape (CR 7) — two Fist attacks at 10-ft reach + Boulder Toss
  // (Recharge 6): a 5-ft-radius DEX-save burst for 7d6 bludgeoning. (Leap +
  // the Boulder Toss Prone-on-fail rider deferred.)
  giant_ape: {
    name: 'Giant Ape',
    cr: 7,
    hp: 168,
    ac: 12,
    damage: '3d10+6',
    toHit: 9,
    xp: 2900,
    str: 23,
    dex: 14,
    con: 18,
    int: 5,
    wis: 12,
    cha: 7,
    multiattack: 2,
    speedFt: 40,
    attackReachFt: 10,
    damageType: 'bludgeoning',
    darkvision_ft: 0, // beast — no darkvision
    breathWeapon: {
      name: 'Boulder Toss',
      dice: '7d6',
      damageType: 'bludgeoning',
      savingThrow: 'dex',
      saveDC: 17,
      rechargeMin: 6, // Recharge 6
    },
  },

  // SRD: Frost Giant (CR 8) — two Frost Axe attacks (slashing + 2d8 cold rider);
  // Cold-immune. (Great Bow + War Cry bonus action deferred.)
  frost_giant: {
    name: 'Frost Giant',
    cr: 8,
    hp: 149,
    ac: 15,
    damage: '2d12+6',
    toHit: 9,
    xp: 3900,
    str: 23,
    dex: 9,
    con: 21,
    int: 9,
    wis: 10,
    cha: 12,
    multiattack: 2,
    speedFt: 40,
    attackReachFt: 10,
    damageType: 'slashing',
    bonusDamage: '2d8',
    bonusDamageType: 'cold',
    immunities: ['cold'],
    darkvision_ft: 0, // no darkvision in its stat block
  },

  // SRD: Fire Giant (CR 9) — two Flame Sword attacks (slashing + 3d6 fire rider);
  // Fire-immune. (Hammer Throw deferred.)
  fire_giant: {
    name: 'Fire Giant',
    cr: 9,
    hp: 162,
    ac: 18,
    damage: '4d6+7',
    toHit: 11,
    xp: 5000,
    str: 25,
    dex: 9,
    con: 23,
    int: 10,
    wis: 14,
    cha: 13,
    multiattack: 2,
    speedFt: 30,
    attackReachFt: 10,
    damageType: 'slashing',
    bonusDamage: '3d6',
    bonusDamageType: 'fire',
    immunities: ['fire'],
    darkvision_ft: 0,
  },

  // SRD: Cloud Giant (CR 9) — two Thunderous Mace attacks (bludgeoning + 2d6
  // thunder rider). (Thundercloud, Spellcasting + Misty Step deferred/narrated.)
  cloud_giant: {
    name: 'Cloud Giant',
    cr: 9,
    hp: 200,
    ac: 14,
    damage: '3d8+8',
    toHit: 12,
    xp: 5000,
    str: 27,
    dex: 10,
    con: 22,
    int: 12,
    wis: 16,
    cha: 16,
    multiattack: 2,
    speedFt: 40,
    attackReachFt: 10,
    damageType: 'bludgeoning',
    bonusDamage: '2d6',
    bonusDamageType: 'thunder',
    darkvision_ft: 0,
  },

  // SRD: Young Red Dragon (CR 10) — three Rend attacks (slashing + 1d6 fire
  // rider) + Fire Breath (Recharge 5–6): a 30-ft cone, DEX save DC 17 for 16d6
  // fire (half on a success). Fire-immune, Blindsight + Darkvision 120, 80-ft
  // fly. (The cone geometry is abstracted to the whole party — see BreathWeapon.)
  young_red_dragon: {
    name: 'Young Red Dragon',
    cr: 10,
    hp: 178,
    ac: 18,
    damage: '2d6+6',
    toHit: 10,
    xp: 5900,
    str: 23,
    dex: 10,
    con: 21,
    int: 14,
    wis: 11,
    cha: 19,
    multiattack: 3,
    speedFt: 80, // fly
    attackReachFt: 10,
    damageType: 'slashing',
    bonusDamage: '1d6',
    bonusDamageType: 'fire',
    immunities: ['fire'],
    darkvision_ft: 120,
    breathWeapon: {
      name: 'Fire Breath',
      dice: '16d6',
      damageType: 'fire',
      savingThrow: 'dex',
      saveDC: 17,
      rechargeMin: 5, // Recharge 5–6
    },
  },
};
