import type { LootItem, PlacedLoot } from '../../types.js';
import { srdItems } from '../srd/index.js';

export const lootTable: LootItem[] = [
  // Shared SRD equipment available in this campaign.
  ...srdItems(
    // Simple weapons (full SRD spread — every class is proficient with these).
    'club',
    'dagger',
    'dart',
    'greatclub',
    'handaxe',
    'javelin',
    'light_hammer',
    'mace',
    'quarterstaff',
    'sickle',
    'spear',
    'light_crossbow',
    'shortbow',
    'sling',
    // Martial weapons with Finesse/Light (Rogue-masterable) + the heavier
    // martials already stocked for Fighter/Barbarian/etc.
    'rapier',
    'scimitar',
    'shortsword',
    'whip',
    'hand_crossbow',
    'greataxe',
    'longsword',
    'longbow',
    'leather_armor',
    'studded_leather',
    'scale_mail',
    'chain_mail',
    'shield',
    'healing_potion',
    'holy_symbol',
    'component_pouch'
  ),
  // SRD equipment from the folded Whispering Pines module (warhammer is the
  // only one not already shared above).
  ...srdItems('warhammer'),
  // Campaign-specific quest items.
  {
    id: 'guild_ledger',
    name: 'Guild Ledger',
    weight: 3,
    desc: "A waterlogged ledger bearing the Merchant Guild's stamp — evidence of the missing shipment.",
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['ledger', 'book', 'shipping records'],
  },
  {
    id: 'shadow_evidence',
    name: 'Incriminating Letter',
    weight: 1,
    desc: "A letter bearing Captain Vane's seal, arranging bribes with the bandits.",
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['letter', 'evidence'],
  },
  {
    id: 'moonstone_amulet',
    name: 'Moonstone Amulet',
    weight: 2,
    desc: 'A silver amulet set with a glowing moonstone. Grants +1 to Wisdom saving throws.',
    type: 'misc',
    slot: 'neck',
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: '+1_wis_save',
    wornEffects: [{ kind: 'save_bonus', ability: 'wis', bonus: 1 }],
    requiresAttunement: true,
    aliases: ['amulet', 'moonstone'],
  },
  {
    id: 'stolen_shipment',
    name: 'Stolen Guild Cargo',
    weight: 6,
    desc: "A crate stamped with the Merchant Guild's mark — part of the shipment raided from the Old Road. Aldric will want this back.",
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['cargo', 'crate', 'shipment', 'goods'],
  },

  // ── Whispering Pines (folded) — campaign-specific items ───────────────────
  {
    id: 'fur_cloak',
    name: 'Fur Cloak',
    weight: 3,
    desc: 'A thick bearskin cloak — warm enough to ride the pass at night.',
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: 'cold_warmth',
    aliases: ['cloak', 'pelt'],
  },
  {
    id: 'elixir_of_warmth',
    name: 'Elixir of Warmth',
    weight: 1,
    desc: 'A clay vial of mulled spirits brewed by the trappers. Restores 1d4+2 HP and steadies the body against cold.',
    type: 'consumable',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: '1d4+2',
    effect: null,
    aliases: ['elixir', 'mulled spirit'],
  },
  {
    id: 'halden_locket',
    name: "Halden's Locket",
    weight: 1,
    desc: "A trapper's silver locket — proof Old Halden was here. His daughter's portrait inside.",
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['locket', "halden's locket"],
  },
  {
    id: 'cult_idol',
    name: 'Frostspire Idol',
    weight: 4,
    desc: "A black ironwood idol carved with the cult's rune. Captain Riese will want to see this.",
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['idol', 'rune', 'cult idol'],
  },

  // ── Grove of Thorns (folded) — campaign-specific items ────────────────────
  {
    id: 'circle_charm',
    name: "Mareth's Charm",
    weight: 0,
    desc: 'An acorn carved with the Verdant Circle sigil. The druid Mareth carried this.',
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    aliases: ['charm', 'acorn', 'mareth charm'],
  },
  {
    id: 'oak_heart',
    name: 'Heart of the Ancient Oak',
    weight: 2,
    desc: "A fist-sized seedpod glowing with green light. The grove's heart, freed from the trickster.",
    type: 'misc',
    slot: null,
    damage: null,
    ac_bonus: null,
    heal: null,
    effect: null,
    requiresAttunement: true,
    aliases: ['heart', 'oak heart', 'seedpod'],
  },
];

// Loot placed in rooms, keyed by room id. Each room holds a list of positioned
// `PlacedLoot` items; `pos` is the local-room grid cell (chosen in-bounds, off
// the entry cell + any obstacles) where the item renders as a clickable token.
const HEALING_POTION = (desc = 'A crimson vial.'): Omit<PlacedLoot, 'pos'> => ({
  id: 'healing_potion',
  name: 'Healing Potion',
  weight: 4,
  desc,
  type: 'consumable',
  slot: null,
  damage: null,
  ac_bonus: null,
  heal: '2d4+2',
  effect: null,
  aliases: ['potion'],
});

export const loot: Record<string, PlacedLoot[]> = {
  // Two vials here — exercises multiple positioned items in one room.
  dungeon_antechamber: [
    { ...HEALING_POTION(), pos: { x: 5, y: 5 } },
    { ...HEALING_POTION('A second crimson vial, half-buried in rubble.'), pos: { x: 7, y: 3 } },
  ],
  dungeon_offering_chamber: [
    {
      id: 'guild_ledger',
      name: 'Guild Ledger',
      weight: 3,
      desc: "A waterlogged ledger bearing the Guild's stamp.",
      type: 'misc',
      slot: null,
      damage: null,
      ac_bonus: null,
      heal: null,
      effect: null,
      aliases: ['ledger'],
      pos: { x: 5, y: 5 },
    },
  ],
  dungeon_ossuary: [{ ...HEALING_POTION(), pos: { x: 5, y: 5 } }],
  dungeon_crypt_throne: [
    {
      id: 'moonstone_amulet',
      name: 'Moonstone Amulet',
      weight: 2,
      desc: 'A glowing moonstone amulet, sacred to Selûne.',
      type: 'misc',
      slot: 'neck',
      damage: null,
      ac_bonus: null,
      heal: null,
      effect: '+1_wis_save',
      wornEffects: [{ kind: 'save_bonus', ability: 'wis', bonus: 1 }],
      requiresAttunement: true,
      aliases: ['amulet'],
      pos: { x: 5, y: 8 },
    },
  ],
  bandit_camp: [
    { ...HEALING_POTION('A crimson vial, looted from the wagon.'), pos: { x: 5, y: 5 } },
  ],
  bandit_tent: [
    {
      id: 'stolen_shipment',
      name: 'Stolen Guild Cargo',
      weight: 6,
      desc: "A crate stamped with the Merchant Guild's mark — the raided Old Road shipment.",
      type: 'misc',
      slot: null,
      damage: null,
      ac_bonus: null,
      heal: null,
      effect: null,
      aliases: ['cargo', 'crate', 'shipment', 'goods'],
      pos: { x: 4, y: 4 },
    },
  ],

  // ── Whispering Pines (folded) ────────────────────────────────────────────
  spire_entrance: [
    {
      id: 'fur_cloak',
      name: 'Fur Cloak',
      weight: 3,
      desc: 'A discarded fur cloak — Halden was here.',
      type: 'misc',
      slot: null,
      damage: null,
      ac_bonus: null,
      heal: null,
      effect: 'cold_warmth',
      aliases: ['cloak'],
      pos: { x: 5, y: 5 },
    },
  ],
  spire_frozen_hall: [
    {
      id: 'elixir_of_warmth',
      name: 'Elixir of Warmth',
      weight: 1,
      desc: 'A clay vial of mulled spirits — restores 1d4+2 HP.',
      type: 'consumable',
      slot: null,
      damage: null,
      ac_bonus: null,
      heal: '1d4+2',
      effect: null,
      aliases: ['elixir'],
      pos: { x: 5, y: 5 },
    },
  ],
  spire_cult_chamber: [
    {
      id: 'halden_locket',
      name: "Halden's Locket",
      weight: 1,
      desc: "Old Halden's silver locket — proof he was here.",
      type: 'misc',
      slot: null,
      damage: null,
      ac_bonus: null,
      heal: null,
      effect: null,
      aliases: ['locket'],
      pos: { x: 5, y: 5 },
    },
  ],
  spire_ritual_apex: [
    {
      id: 'cult_idol',
      name: 'Frostspire Idol',
      weight: 4,
      desc: 'A black ironwood idol carved with the cult rune. Captain Riese will want this.',
      type: 'misc',
      slot: null,
      damage: null,
      ac_bonus: null,
      heal: null,
      effect: null,
      aliases: ['idol', 'rune'],
      pos: { x: 5, y: 8 },
    },
  ],

  // ── Grove of Thorns (folded) ─────────────────────────────────────────────
  pinegate_lodge: [
    {
      id: 'circle_charm',
      name: "Mareth's Charm",
      weight: 0,
      desc: 'An acorn carved with the Verdant Circle sigil. Mareth left it before she vanished.',
      type: 'misc',
      slot: null,
      damage: null,
      ac_bonus: null,
      heal: null,
      effect: null,
      aliases: ['charm', 'acorn'],
      pos: { x: 3, y: 2 },
    },
  ],
  grove_sanctum: [
    {
      id: 'oak_heart',
      name: 'Heart of the Ancient Oak',
      weight: 2,
      desc: "The grove's heart, restored. Pulses warm and green.",
      type: 'misc',
      slot: null,
      damage: null,
      ac_bonus: null,
      heal: null,
      effect: null,
      requiresAttunement: true,
      aliases: ['heart', 'oak heart'],
      pos: { x: 4, y: 4 },
    },
  ],
};
