import type { EnemyTemplate } from '../../types.js';

// Shared SRD bestiary entries.
//
// 5e bestiary stat blocks are universal — a Goblin in Vale of Shadows is the
// same Goblin in Whispering Pines. Pansori previously duplicated these
// definitions across every campaign context; this registry is the single
// source of truth.
//
// Contexts spread an entry and override what's themed for the campaign:
//
//   enemyTemplates: [
//     { ...SRD_MONSTERS.skeleton, name: 'Skeleton Warrior', resistances: ['piercing'] },
//     { ...SRD_MONSTERS.wolf, name: 'Frost Wolf', resistances: ['cold'] },
//   ],
//
// Bosses and campaign-unique creatures (Crypt Lord, Frost Acolyte, Fey
// Trickster, Frost Cultist, etc.) stay inline in their context — they aren't
// SRD baseline and don't generalize across campaigns.
//
// Stat blocks follow SRD 5.2.1 where available. Numeric stats match the
// printed monster manual entries; campaigns add cosmetic deltas
// (name/damageType/resistances) without re-stating the math.

// Helper type — the `name` field gets overridden by every campaign anyway,
// so the base entries supply a default name that callers can replace.
type SrdMonster = EnemyTemplate;

export const SRD_MONSTERS: Record<string, SrdMonster> = {
  // ─── CR 1/8 ────────────────────────────────────────────────────────────────
  bandit: {
    name: 'Bandit',
    cr: 0.125,
    hp: 11,
    ac: 12,
    damage: '1d6+1',
    toHit: 3,
    xp: 25,
    str: 11,
    dex: 12,
    con: 12,
    int: 10,
    wis: 10,
    cha: 10,
    damageType: 'slashing',
  },

  // ─── CR 1/4 ────────────────────────────────────────────────────────────────
  goblin: {
    name: 'Goblin',
    cr: 0.25,
    hp: 7,
    ac: 15,
    damage: '1d6+2',
    toHit: 4,
    xp: 50,
    str: 8,
    dex: 14,
    con: 10,
    int: 10,
    wis: 8,
    cha: 8,
  },
  skeleton: {
    name: 'Skeleton',
    cr: 0.25,
    hp: 13,
    ac: 13,
    damage: '1d6+2',
    toHit: 4,
    xp: 50,
    str: 10,
    dex: 14,
    con: 15,
    int: 6,
    wis: 8,
    cha: 5,
    vulnerabilities: ['bludgeoning'],
    immunities: ['poison'],
    condition_immunities: ['poisoned', 'exhaustion'],
  },
  wolf: {
    name: 'Wolf',
    cr: 0.25,
    hp: 11,
    ac: 13,
    damage: '1d6+1',
    toHit: 4,
    xp: 50,
    str: 12,
    dex: 15,
    con: 12,
    int: 3,
    wis: 12,
    cha: 6,
    damageType: 'piercing',
  },
  giant_spider: {
    name: 'Giant Spider',
    cr: 0.25,
    hp: 13,
    ac: 14,
    damage: '1d8',
    toHit: 5,
    xp: 100,
    str: 8,
    dex: 16,
    con: 11,
    int: 2,
    wis: 11,
    cha: 4,
    onHitEffect: { condition: 'poisoned', ability: 'con', dc: 11 },
    damageType: 'piercing',
  },

  // ─── CR 1/2 ────────────────────────────────────────────────────────────────
  orc: {
    name: 'Orc',
    cr: 0.5,
    hp: 15,
    ac: 13,
    damage: '1d12+3',
    toHit: 5,
    xp: 100,
    str: 16,
    dex: 12,
    con: 16,
    int: 7,
    wis: 11,
    cha: 10,
  },
  shadow: {
    name: 'Shadow',
    cr: 0.5,
    hp: 16,
    ac: 12,
    damage: '2d6+2',
    toHit: 4,
    xp: 100,
    str: 6,
    dex: 14,
    con: 13,
    int: 6,
    wis: 10,
    cha: 8,
    resistances: [
      'acid',
      'fire',
      'thunder',
      'lightning',
      'cold',
      'bludgeoning',
      'piercing',
      'slashing',
    ],
    immunities: ['necrotic', 'poison'],
    condition_immunities: [
      'exhaustion',
      'frightened',
      'grappled',
      'paralyzed',
      'petrified',
      'poisoned',
      'prone',
      'restrained',
    ],
    damageType: 'necrotic',
  },
  ice_mephit: {
    name: 'Ice Mephit',
    cr: 0.5,
    hp: 21,
    ac: 11,
    damage: '1d4+2',
    toHit: 4,
    xp: 100,
    str: 7,
    dex: 13,
    con: 10,
    int: 9,
    wis: 11,
    cha: 12,
    immunities: ['cold'],
    vulnerabilities: ['fire'],
    condition_immunities: ['poisoned'],
    damageType: 'cold',
  },

  // ─── CR 1 ──────────────────────────────────────────────────────────────────
  ghoul: {
    name: 'Ghoul',
    cr: 1,
    hp: 22,
    ac: 13,
    damage: '2d6+2',
    toHit: 4,
    xp: 200,
    str: 13,
    dex: 15,
    con: 10,
    int: 7,
    wis: 10,
    cha: 6,
    onHitEffect: { condition: 'paralyzed', ability: 'con', dc: 10 },
    condition_immunities: ['poisoned', 'charmed'],
    damageType: 'piercing',
  },
  brown_bear: {
    name: 'Brown Bear',
    cr: 1,
    hp: 34,
    ac: 11,
    damage: '2d6+4',
    toHit: 5,
    xp: 200,
    str: 19,
    dex: 10,
    con: 16,
    int: 2,
    wis: 13,
    cha: 7,
    multiattack: 2,
    damageType: 'slashing',
  },

  // ─── CR 2 ──────────────────────────────────────────────────────────────────
  cult_fanatic: {
    name: 'Cult Fanatic',
    cr: 2,
    hp: 33,
    ac: 13,
    damage: '1d4+2',
    toHit: 4,
    xp: 450,
    str: 9,
    dex: 14,
    con: 11,
    int: 12,
    wis: 14,
    cha: 14,
    onHitEffect: { condition: 'poisoned', ability: 'con', dc: 13 },
  },
  ogre: {
    name: 'Ogre',
    cr: 2,
    hp: 59,
    ac: 11,
    damage: '2d8+4',
    toHit: 6,
    xp: 450,
    str: 19,
    dex: 8,
    con: 16,
    int: 5,
    wis: 7,
    cha: 7,
    multiattack: 2,
  },
};
