import type { EnemyTemplate } from '../../types.js';

// Shared SRD bestiary entries.
//
// 5e bestiary stat blocks are universal — a Goblin in Vale of Shadows is the
// same Goblin in Whispering Pines. Pansori previously duplicated these
// definitions across every campaign context; this registry is the single
// source of truth.
//
// Contexts spread an entry and override what's themed for the campaign:
//
//   enemyTemplates: [
//     { ...SRD_MONSTERS.skeleton, name: 'Skeleton Warrior', resistances: ['piercing'] },
//     { ...SRD_MONSTERS.wolf, name: 'Frost Wolf', resistances: ['cold'] },
//   ],
//
// Bosses and campaign-unique creatures (Crypt Lord, Frost Acolyte, Fey
// Trickster, Frost Cultist, etc.) stay inline in their context — they aren't
// SRD baseline and don't generalize across campaigns.
//
// Stat blocks follow SRD 5.2.1 where available. Numeric stats match the
// printed monster manual entries; campaigns add cosmetic deltas
// (name/damageType/resistances) without re-stating the math.

// Helper type — the `name` field gets overridden by every campaign anyway,
// so the base entries supply a default name that callers can replace.
type SrdMonster = EnemyTemplate;

export const SRD_MONSTERS: Record<string, SrdMonster> = {
  // ─── CR 1/8 ────────────────────────────────────────────────────────────────
  bandit: {
    name: 'Bandit',
    cr: 0.125,
    hp: 11,
    ac: 12,
    damage: '1d6+1',
    toHit: 3,
    xp: 25,
    str: 11,
    dex: 12,
    con: 12,
    int: 10,
    wis: 10,
    cha: 10,
    damageType: 'slashing',
  },

  // ─── CR 1/4 ────────────────────────────────────────────────────────────────
  goblin: {
    name: 'Goblin',
    cr: 0.25,
    hp: 7,
    ac: 15,
    damage: '1d6+2',
    toHit: 4,
    xp: 50,
    str: 8,
    dex: 14,
    con: 10,
    int: 10,
    wis: 8,
    cha: 8,
  },
  skeleton: {
    name: 'Skeleton',
    cr: 0.25,
    hp: 13,
    ac: 13,
    damage: '1d6+2',
    toHit: 4,
    xp: 50,
    str: 10,
    dex: 14,
    con: 15,
    int: 6,
    wis: 8,
    cha: 5,
    vulnerabilities: ['bludgeoning'],
    immunities: ['poison'],
    condition_immunities: ['poisoned', 'exhaustion'],
  },
  wolf: {
    name: 'Wolf',
    cr: 0.25,
    hp: 11,
    ac: 13,
    damage: '1d6+1',
    toHit: 4,
    xp: 50,
    str: 12,
    dex: 15,
    con: 12,
    int: 3,
    wis: 12,
    cha: 6,
    packTactics: true,
    damageType: 'piercing',
  },
  giant_spider: {
    name: 'Giant Spider',
    cr: 0.25,
    hp: 13,
    ac: 14,
    damage: '1d8',
    toHit: 5,
    xp: 100,
    str: 8,
    dex: 16,
    con: 11,
    int: 2,
    wis: 11,
    cha: 4,
    onHitEffect: { condition: 'poisoned', ability: 'con', dc: 11 },
    damageType: 'piercing',
  },

  // ─── CR 1/2 ────────────────────────────────────────────────────────────────
  orc: {
    name: 'Orc',
    cr: 0.5,
    hp: 15,
    ac: 13,
    damage: '1d12+3',
    toHit: 5,
    xp: 100,
    str: 16,
    dex: 12,
    con: 16,
    int: 7,
    wis: 11,
    cha: 10,
  },
  shadow: {
    name: 'Shadow',
    cr: 0.5,
    hp: 16,
    ac: 12,
    damage: '2d6+2',
    toHit: 4,
    xp: 100,
    str: 6,
    dex: 14,
    con: 13,
    int: 6,
    wis: 10,
    cha: 8,
    resistances: [
      'acid',
      'fire',
      'thunder',
      'lightning',
      'cold',
      'bludgeoning',
      'piercing',
      'slashing',
    ],
    immunities: ['necrotic', 'poison'],
    condition_immunities: [
      'exhaustion',
      'frightened',
      'grappled',
      'paralyzed',
      'petrified',
      'poisoned',
      'prone',
      'restrained',
    ],
    damageType: 'necrotic',
  },
  ice_mephit: {
    name: 'Ice Mephit',
    cr: 0.5,
    hp: 21,
    ac: 11,
    damage: '1d4+2',
    toHit: 4,
    xp: 100,
    str: 7,
    dex: 13,
    con: 10,
    int: 9,
    wis: 11,
    cha: 12,
    immunities: ['cold'],
    vulnerabilities: ['fire'],
    condition_immunities: ['poisoned'],
    damageType: 'cold',
  },

  // ─── CR 1 ──────────────────────────────────────────────────────────────────
  ghoul: {
    name: 'Ghoul',
    cr: 1,
    hp: 22,
    ac: 13,
    damage: '2d6+2',
    toHit: 4,
    xp: 200,
    str: 13,
    dex: 15,
    con: 10,
    int: 7,
    wis: 10,
    cha: 6,
    onHitEffect: { condition: 'paralyzed', ability: 'con', dc: 10 },
    condition_immunities: ['poisoned', 'charmed'],
    damageType: 'piercing',
  },
  brown_bear: {
    name: 'Brown Bear',
    cr: 1,
    hp: 34,
    ac: 11,
    damage: '2d6+4',
    toHit: 5,
    xp: 200,
    str: 19,
    dex: 10,
    con: 16,
    int: 2,
    wis: 13,
    cha: 7,
    multiattack: 2,
    damageType: 'slashing',
  },

  // ─── CR 2 ──────────────────────────────────────────────────────────────────
  cult_fanatic: {
    name: 'Cult Fanatic',
    cr: 2,
    hp: 33,
    ac: 13,
    damage: '1d4+2',
    toHit: 4,
    xp: 450,
    str: 9,
    dex: 14,
    con: 11,
    int: 12,
    wis: 14,
    cha: 14,
    onHitEffect: { condition: 'poisoned', ability: 'con', dc: 13 },
  },
  ogre: {
    name: 'Ogre',
    cr: 2,
    hp: 59,
    ac: 11,
    damage: '2d8+4',
    toHit: 6,
    xp: 450,
    str: 19,
    dex: 8,
    con: 16,
    int: 5,
    wis: 7,
    cha: 7,
    multiattack: 2,
  },

  // ─── More CR 1/8 ─────────────────────────────────────────────────────────────
  // Pack Tactics / Sunlight Sensitivity (Kobold, Giant Rat) deferred — no
  // ally-adjacency advantage / lighting model yet.
  kobold: {
    name: 'Kobold',
    cr: 0.125,
    hp: 7,
    ac: 14,
    damage: '1d4+2',
    toHit: 4,
    xp: 25,
    str: 7,
    dex: 15,
    con: 9,
    int: 8,
    wis: 7,
    cha: 8,
    packTactics: true,
    damageType: 'piercing',
  },
  guard: {
    name: 'Guard',
    cr: 0.125,
    hp: 11,
    ac: 16,
    damage: '1d6+1',
    toHit: 3,
    xp: 25,
    str: 13,
    dex: 12,
    con: 12,
    int: 10,
    wis: 11,
    cha: 10,
    damageType: 'piercing',
  },
  cultist: {
    name: 'Cultist',
    cr: 0.125,
    hp: 9,
    ac: 12,
    damage: '1d4+1',
    toHit: 3,
    xp: 25,
    str: 11,
    dex: 12,
    con: 10,
    int: 10,
    wis: 11,
    cha: 10,
    damageType: 'slashing',
    bonusDamage: '1', // Ritual Sickle: +1 Necrotic
    bonusDamageType: 'necrotic',
  },
  giant_rat: {
    name: 'Giant Rat',
    cr: 0.125,
    hp: 7,
    ac: 13,
    damage: '1d4+3',
    toHit: 5,
    xp: 25,
    str: 7,
    dex: 16,
    con: 11,
    int: 2,
    wis: 10,
    cha: 4,
    packTactics: true,
    damageType: 'piercing',
  },

  // ─── More CR 1/4 ─────────────────────────────────────────────────────────────
  zombie: {
    name: 'Zombie',
    cr: 0.25,
    hp: 15,
    ac: 8,
    damage: '1d6+1',
    toHit: 3,
    xp: 50,
    str: 13,
    dex: 6,
    con: 16,
    int: 3,
    wis: 6,
    cha: 5,
    immunities: ['poison'],
    condition_immunities: ['poisoned', 'exhaustion'],
    damageType: 'bludgeoning',
    // Undead Fortitude — a non-Radiant, non-Crit hit that would drop it to 0
    // HP lets it make a CON save (DC 5 + damage) to cling to 1 HP instead.
    undeadFortitude: true,
  },

  // ─── More CR 1/2 ─────────────────────────────────────────────────────────────
  scout: {
    name: 'Scout',
    cr: 0.5,
    hp: 16,
    ac: 13,
    damage: '1d6+2',
    toHit: 4,
    xp: 100,
    str: 11,
    dex: 14,
    con: 12,
    int: 11,
    wis: 13,
    cha: 11,
    multiattack: 2,
    damageType: 'piercing',
  },
  worg: {
    name: 'Worg',
    cr: 0.5,
    hp: 26,
    ac: 13,
    damage: '1d8+3',
    toHit: 5,
    xp: 100,
    str: 16,
    dex: 13,
    con: 13,
    int: 7,
    wis: 11,
    cha: 8,
    speedFt: 50,
    packTactics: true,
    damageType: 'piercing',
  },
  gnoll: {
    name: 'Gnoll',
    cr: 0.5,
    hp: 27,
    ac: 15,
    damage: '1d6+2',
    toHit: 4,
    xp: 100,
    str: 14,
    dex: 12,
    con: 11,
    int: 6,
    wis: 10,
    cha: 7,
    damageType: 'piercing',
  },
  black_bear: {
    name: 'Black Bear',
    cr: 0.5,
    hp: 19,
    ac: 11,
    damage: '1d6+2',
    toHit: 4,
    xp: 100,
    str: 15,
    dex: 12,
    con: 14,
    int: 2,
    wis: 12,
    cha: 7,
    multiattack: 2,
    damageType: 'slashing',
  },

  // ─── More CR 1 ───────────────────────────────────────────────────────────────
  dire_wolf: {
    name: 'Dire Wolf',
    cr: 1,
    hp: 22,
    ac: 14,
    damage: '1d8+3',
    toHit: 5,
    xp: 200,
    str: 17,
    dex: 15,
    con: 15,
    int: 3,
    wis: 12,
    cha: 7,
    speedFt: 50,
    packTactics: true,
    damageType: 'piercing',
  },
  specter: {
    name: 'Specter',
    cr: 1,
    hp: 22,
    ac: 12,
    // Life Drain — necrotic damage only (its max-HP reduction rider is deferred).
    damage: '3d6',
    toHit: 4,
    xp: 200,
    str: 1,
    dex: 14,
    con: 11,
    int: 10,
    wis: 10,
    cha: 11,
    resistances: [
      'acid',
      'bludgeoning',
      'cold',
      'fire',
      'lightning',
      'piercing',
      'slashing',
      'thunder',
    ],
    immunities: ['necrotic', 'poison'],
    condition_immunities: [
      'charmed',
      'exhaustion',
      'grappled',
      'paralyzed',
      'petrified',
      'poisoned',
      'prone',
      'restrained',
      'unconscious',
    ],
    speedFt: 50, // hovering flight
    damageType: 'necrotic',
  },
  animated_armor: {
    name: 'Animated Armor',
    cr: 1,
    hp: 33,
    ac: 18,
    damage: '1d6+2',
    toHit: 4,
    xp: 200,
    str: 14,
    dex: 11,
    con: 13,
    int: 1,
    wis: 3,
    cha: 1,
    multiattack: 2,
    immunities: ['poison', 'psychic'],
    condition_immunities: [
      'charmed',
      'deafened',
      'exhaustion',
      'frightened',
      'paralyzed',
      'petrified',
      'poisoned',
    ],
    speedFt: 25,
    damageType: 'bludgeoning',
  },

  // ─── More CR 2 ───────────────────────────────────────────────────────────────
  bandit_captain: {
    name: 'Bandit Captain',
    cr: 2,
    hp: 52,
    ac: 15,
    damage: '1d6+3',
    toHit: 5,
    xp: 450,
    str: 15,
    dex: 16,
    con: 14,
    int: 14,
    wis: 11,
    cha: 14,
    multiattack: 2,
    damageType: 'slashing',
    // Parry reaction deferred.
  },
  berserker: {
    name: 'Berserker',
    cr: 2,
    hp: 67,
    ac: 13,
    damage: '1d12+3',
    toHit: 5,
    xp: 450,
    str: 16,
    dex: 12,
    con: 17,
    int: 9,
    wis: 11,
    cha: 9,
    bloodiedFrenzy: true,
    damageType: 'slashing',
  },
  ghast: {
    name: 'Ghast',
    cr: 2,
    hp: 36,
    ac: 13,
    damage: '2d6+3',
    toHit: 5,
    xp: 450,
    str: 16,
    dex: 17,
    con: 10,
    int: 11,
    wis: 10,
    cha: 8,
    onHitEffect: { condition: 'paralyzed', ability: 'con', dc: 10 },
    resistances: ['necrotic'],
    immunities: ['poison'],
    condition_immunities: ['charmed', 'exhaustion', 'poisoned'],
    damageType: 'slashing',
    bonusDamage: '2d8', // claw rider ≈ the bite's necrotic
    bonusDamageType: 'necrotic',
    // Stench aura deferred.
  },
  griffon: {
    name: 'Griffon',
    cr: 2,
    hp: 59,
    ac: 12,
    damage: '1d8+4',
    toHit: 6,
    xp: 450,
    str: 18,
    dex: 15,
    con: 16,
    int: 2,
    wis: 13,
    cha: 8,
    multiattack: 2,
    speedFt: 80, // flight
    damageType: 'piercing',
  },

  // ─── More CR 3 ───────────────────────────────────────────────────────────────
  owlbear: {
    name: 'Owlbear',
    cr: 3,
    hp: 59,
    ac: 13,
    damage: '2d8+5',
    toHit: 7,
    xp: 700,
    str: 20,
    dex: 12,
    con: 17,
    int: 3,
    wis: 12,
    cha: 7,
    multiattack: 2,
    speedFt: 40,
    damageType: 'slashing',
  },
  manticore: {
    name: 'Manticore',
    cr: 3,
    hp: 68,
    ac: 14,
    damage: '1d8+3',
    toHit: 5,
    xp: 700,
    str: 17,
    dex: 16,
    con: 17,
    int: 7,
    wis: 12,
    cha: 8,
    multiattack: 3, // Rend / Tail Spike in any combination
    damageType: 'slashing',
  },
  wight: {
    name: 'Wight',
    cr: 3,
    hp: 82,
    ac: 14,
    damage: '1d8+2',
    toHit: 4,
    xp: 700,
    str: 15,
    dex: 14,
    con: 16,
    int: 10,
    wis: 13,
    cha: 15,
    multiattack: 2,
    resistances: ['necrotic'],
    immunities: ['poison'],
    condition_immunities: ['exhaustion', 'poisoned'],
    damageType: 'slashing',
    bonusDamage: '1d8', // Necrotic Sword rider
    bonusDamageType: 'necrotic',
    // Life Drain (max-HP reduction) deferred.
  },
};
