/**
 * Sync src/shared/types.ts into each workspace as `shared-types.ts`.
 *
 * Why this exists: the backend and frontend live in separate npm
 * workspaces with separate Docker bind-mounts, so a real shared
 * package would need a wider Docker build context and per-workspace
 * dependency wiring. This script is simpler — one source of truth,
 * one mechanical copy, no Docker / npm-workspace churn.
 *
 * Usage:
 *   tsx scripts/sync-shared-types.ts           # write the copies
 *   tsx scripts/sync-shared-types.ts --check   # exit 1 if copies are stale
 *
 * Hooked into root package.json as `prebuild` / `predev` / `pretest`
 * so the dev/test/build paths can't run with stale copies. CI runs
 * `npm run sync-types:check` to catch drift in PRs.
 */

import { dirname, join, relative } from 'path';
import { fileURLToPath } from 'url';
import { readFileSync, writeFileSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = join(__dirname, '..');
const sourcePath = join(repoRoot, 'src/shared/types.ts');
const targets = [
  join(repoRoot, 'src/backend/src/shared-types.ts'),
  join(repoRoot, 'src/frontend/src/shared-types.ts'),
];

const HEADER_LINES = [
  '// ─────────────────────────────────────────────────────────────────────',
  '// AUTO-GENERATED FROM src/shared/types.ts — DO NOT EDIT THIS FILE.',
  '// Run `npm run sync-types` after editing the source-of-truth.',
  '// CI runs `npm run sync-types:check` and fails the build on drift.',
  '// ─────────────────────────────────────────────────────────────────────',
  '',
];

function buildOutput(sourceContents: string): string {
  return HEADER_LINES.join('\n') + sourceContents;
}

function main(): void {
  const checkMode = process.argv.includes('--check');

  let source: string;
  try {
    source = readFileSync(sourcePath, 'utf-8');
  } catch (err) {
    console.error(
      `sync-shared-types: cannot read source ${relative(repoRoot, sourcePath)}:`,
      (err as Error).message
    );
    process.exit(2);
  }

  const expected = buildOutput(source);
  let drift = false;

  for (const target of targets) {
    const rel = relative(repoRoot, target);
    if (checkMode) {
      let actual: string;
      try {
        actual = readFileSync(target, 'utf-8');
      } catch {
        console.error(`sync-shared-types: missing copy at ${rel}`);
        drift = true;
        continue;
      }
      if (actual !== expected) {
        console.error(`sync-shared-types: ${rel} is out of sync with src/shared/types.ts`);
        drift = true;
      }
    } else {
      writeFileSync(target, expected);
      console.log(`sync-shared-types: wrote ${rel}`);
    }
  }

  if (drift) {
    console.error('sync-shared-types: run `npm run sync-types` and commit the result.');
    process.exit(1);
  }
}

main();
