-- (no-op) Example-campaign seed removed 2026-06-09.
--
-- This migration originally seeded two built-in campaigns (sandbox + malgovia)
-- as DB rows. The project is now campaign-agnostic: campaigns are authored
-- through the creator/content API (or, for the e2e suite, planted at test time
-- by the gated POST /api/test/seed-campaign endpoint into a throwaway, ephemeral
-- database). Nothing ships a built-in campaign.
--
-- The body is intentionally empty rather than the file deleted: the migration
-- runner tracks applied files by filename, so existing databases have already
-- recorded this id and skip it; fresh databases run this no-op. Removal of the
-- rows from previously-seeded databases is handled by
-- 039_remove_example_campaigns.sql.
