// ─────────────────────────────────────────────────────────────────────
// AUTO-GENERATED FROM src/shared/types.ts — DO NOT EDIT THIS FILE.
// Run `npm run sync-types` after editing the source-of-truth.
// CI runs `npm run sync-types:check` and fails the build on drift.
// ─────────────────────────────────────────────────────────────────────
// Cross-cutting types shared between the backend (`src/backend/src/`) and
// the frontend (`src/frontend/src/`). This is the single source of truth.
//
// A small sync script (`scripts/sync-shared-types.ts`) copies this file
// into each workspace as `shared-types.ts`, prefixed with an "AUTO-
// GENERATED — do not edit" header. Both `src/backend/src/types.ts` and
// `src/frontend/src/types.ts` re-export from their local copy.
//
// Why not a workspaces package? Each Docker dev container bind-mounts
// only its own workspace; adding a shared package would require
// rewiring Dockerfile build contexts and reworking the npm-install
// flow. The sync-script approach is one file, no Docker changes, and
// has a `--check` mode for CI to catch drift.
//
// What's NOT in here (phase 3, deferred):
//   - `Character`, `GameState` — BE has rich runtime fields; FE has slim
//     subsets. Unifying needs case-by-case decisions on whether to expand
//     FE or slim BE.
//   - `Seed`, `Location`, `Trap`, `Room` — depend on BE-only types
//     (`Enemy`, `BossPhase`, `OnHitEffect`) that would cascade-share.
//   - `Context` vs `FrontendContext` — intentionally separate (BE has
//     `lootTable` / `spellTable` / etc.; FE has `theme` / `art` / etc.).
//   - `EnemyTemplate`, `Enemy`, `Spell`, `BeastForm`, `GameRule`,
//     `RuleFacts`, `CampaignFacts` — BE-only game-engine internals.

// ─── Atoms ───────────────────────────────────────────────────────────

export type AbilityKey = 'str' | 'dex' | 'con' | 'int' | 'wis' | 'cha';

export type WeaponMastery =
  | 'vex' // advantage on next attack vs target this turn/next
  | 'topple' // CON save or prone on hit
  | 'push' // push target 10 ft on hit
  | 'sap' // disadvantage on target's next attack
  | 'slow' // target's speed -10 ft until your next turn
  | 'nick' // bonus-action TWF attack folded into Attack action
  | 'cleave' // hit second target in 5 ft on a hit
  | 'graze'; // missed attack still deals ability-mod damage

export type ConditionName =
  | 'paralyzed'
  | 'stunned'
  | 'poisoned'
  | 'prone'
  | 'frightened'
  | 'blinded'
  | 'restrained'
  | 'incapacitated'
  | 'grappled'
  | 'invisible'
  | 'exhaustion'
  | 'charmed'
  | 'unconscious'
  | 'deafened'
  | 'petrified'
  // SRD Faerie Fire — outlined creature. Attacks against it
  // have advantage. Engine-internal marker, not in the SRD 14
  // standard conditions list.
  | 'faerie_fired'
  // SRD Banishment — target is sent to a harmless demiplane.
  // While banished, the creature is removed from combat: skipped
  // by the enemy turn loop, filtered out of player attack-target
  // selection, can't be hit or healed. Cleared when the caster's
  // concentration drops (or the 1-minute timer expires); the
  // creature returns to its space. Linked to caster via
  // `concentrating_on.condition = 'banished'`.
  | 'banished'
  // SRD Polymorph — target is transformed into a small beast.
  // The creature stays on the grid + can be attacked; their HP is
  // replaced with the beast form's pool (originals stashed on
  // `entity.polymorph_state`). Enemy turn loop skips polymorphed
  // entities (RAW: they retain their personality but use the new
  // form's actions — pansori MVP skips for simplicity). Cleared
  // by concentration drop, which also restores the original HP.
  | 'polymorphed'
  // SRD Haste — Speed doubled, +2 AC, advantage on Dex saves,
  // and an extra limited action each turn (extra action deferred in
  // pansori MVP). effectiveSpeed reads this flag; computeTotalAc
  // adds +2; rollConditionSave gives advantage on Dex. When the
  // caster's concentration drops, the lethargy hook applies
  // `incapacitated` for one round per RAW.
  | 'hasted'
  // SRD Slow — Speed halved, -2 AC, -2 Dex saves, no reactions,
  // and capped action economy each turn (action-economy gate
  // deferred in pansori MVP behind the same turn-flow refactor that
  // Haste's extra action needs). effectiveSpeed halves speed when
  // the flag is set; toHit pipeline subtracts 2 from the target's
  // effective AC; rollConditionSave subtracts 2 from Dex saves.
  | 'slowed'
  // SRD: Bane — the target subtracts 1d4 from attack rolls and
  // saves for the spell's concentration duration. Mirror of the
  // engine-internal 'blessed' flag. toHit subtracts 1d4 from the
  // attack roll; rollConditionSave subtracts 1d4 from the save.
  | 'baned'
  // SRD: Beacon of Hope — the target has advantage on WIS saves
  // and death saves for the spell's concentration duration.
  // rollConditionSave reads this for WIS-save advantage; the death-
  // save handler reads it for advantage on the d20.
  | 'hopeful'
  // SRD: Command — the target failed its Wisdom save and is compelled
  // to obey a one-word command on its next turn. Pansori models the
  // "Halt" command (the most general "lose your turn" outcome): the
  // enemy turn loop skips a commanded creature's next turn, then
  // consumes the condition (the command applies for one turn only, so
  // the creature acts normally the round after). Single-target, no
  // concentration — distinct from the lasting incapacitating conditions.
  | 'commanded'
  // SRD: Confusion — the target failed its Wisdom save against the 10-ft
  // sphere and behaves erratically. The enemy turn loop rolls 1d10 for a
  // confused creature each turn: it loses the turn, lashes out at a random
  // ally in reach (friendly fire), or (rarely) acts normally. The creature
  // re-saves each turn to shake the effect; cleared by the caster's
  // concentration ending. Applied to all failed-save targets via the
  // opt-in `aoeCondition` cast path.
  | 'confused'
  // SRD: Compulsion — the target failed its Wisdom save and is magically
  // driven to flee. On its turn the enemy loop forces it to use its full
  // movement to stagger away from the caster (no action), then it re-saves;
  // success ends the effect. Concentration; cleared by breakConcentration.
  | 'compelled'
  // SRD: Dominate (Beast/Person/Monster) — the target failed its Wisdom save
  // (rolled with Advantage while the party fights it) and is under the caster's
  // control. On its turn the enemy loop drives it to attack the nearest OTHER
  // enemy (it fights for the party). Concentration; cleared by
  // breakConcentration. (On-damage re-save + manual command surface deferred.)
  | 'dominated'
  // SRD: Blur — the caster's body is blurred; any creature has Disadvantage on
  // attack rolls against them. Self-buff under Concentration; read via
  // `ENEMY_DISADV_CONDITIONS` (imposesDisadvantageOnAttackers) in the enemy
  // attack path, like `invisible`. Cleared by breakConcentration.
  | 'blurred'
  // SRD: Holy Aura — a warded ally: attackers have Disadvantage against it
  // (`imposesDisadvantageOnAttackers`) and it has Advantage on ALL saving throws
  // (a literal `holy_warded` check in rollConditionSave, like `hopeful`).
  // Party-wide, applied by the buff path; cleared by breakConcentration + at
  // combat end.
  | 'holy_warded'
  // SRD: Bestow Curse — a generic hindering curse; the cursed creature attacks
  // at Disadvantage (`imposesDisadvantageOnSelfAttacks`). Concentration-linked,
  // cleared by breakConcentration. (RAW's choice of curse effects is abstracted
  // to this one debuff.)
  | 'cursed'
  // SRD: Heat Metal — a creature seared by the superheated metal attacks at
  // Disadvantage until the start of the caster's next turn (≈ 1 round).
  | 'heat_seared'
  // SRD: Ray of Enfeeblement — an enervated creature attacks at Disadvantage
  // (`imposesDisadvantageOnSelfAttacks`); save-ends each turn, concentration-
  // linked. (RAW's −1d8 weapon damage rider is narrated, not modeled.)
  | 'enfeebled'
  // SRD: Phantasmal Force — a benign carrier condition (no attack/defense
  // effect of its own) marking a creature that perceives a damaging illusion.
  // It drives the recurring save-ends damage tick (the creature takes the
  // spell's psychic damage each failed end-of-turn INT save) and is cleared the
  // moment that save succeeds. Concentration-linked.
  | 'phantasm';

export type NpcAttitude = 'friendly' | 'indifferent' | 'hostile';

export type CoverLevel = 'none' | 'half' | 'three_quarters' | 'full';

export type QuestStatus = 'available' | 'active' | 'completed' | 'failed';

// ─── Grid + combat entity ────────────────────────────────────────────

export interface GridPos {
  x: number;
  y: number;
}

// SRD overland terrain. The single source of truth for a region/town square:
// passability, travel-time multiplier, and random-encounter multiplier are all
// derived from the type (see `TERRAIN`). Replaces the old untyped
// `obstacles[]` / `difficultTerrain[]` arrays on the overland map (those remain
// honored for back-compat). Unlisted squares default to `plains`.
export type TerrainType =
  | 'plains'
  | 'road'
  | 'forest'
  | 'hills'
  | 'swamp'
  | 'snow'
  | 'water'
  | 'mountain'
  // Town-cosmetic types: flavor for settlement maps only. They carry neutral
  // travel/encounter values (town navigation is free-pathfind with no travel
  // cost or encounter rolls — those only apply to regional overland travel), so
  // their tooltips read as a plain label. `town_wall` is impassable.
  | 'cobblestone'
  | 'garden'
  | 'town_wall';

export interface TerrainCell {
  pos: GridPos;
  type: TerrainType;
}

// Behaviour table for each terrain type — shared so the backend (movement /
// travel-time / encounter rolls) and the frontend (passability + rendering)
// agree on one definition.
//  - `passable`: false ⇒ the square blocks travel (water, mountains).
//  - `travelMult`: per-square travel-time multiplier (roads are quick, forest /
//    swamp are slow "difficult terrain").
//  - `encounterMult`: scales the region's per-square encounter chance. Roads
//    are the SAFEST passable terrain but not immune (low, nonzero); wilder
//    terrain is progressively more dangerous. Town-cosmetic types are 0 — and
//    note encounters only roll on the REGIONAL grid (towns / local rooms never
//    roll, regardless of terrain).
export interface TerrainSpec {
  passable: boolean;
  travelMult: number;
  encounterMult: number;
  label: string;
}

export const TERRAIN: Record<TerrainType, TerrainSpec> = {
  plains: { passable: true, travelMult: 1, encounterMult: 1.5, label: 'plains' },
  road: { passable: true, travelMult: 0.5, encounterMult: 0.5, label: 'road' },
  forest: { passable: true, travelMult: 2, encounterMult: 2.5, label: 'forest' },
  hills: { passable: true, travelMult: 1.5, encounterMult: 2, label: 'hills' },
  swamp: { passable: true, travelMult: 2, encounterMult: 2.5, label: 'swamp' },
  snow: { passable: true, travelMult: 1.5, encounterMult: 1.5, label: 'snow' },
  water: { passable: false, travelMult: 1, encounterMult: 0, label: 'water' },
  mountain: { passable: false, travelMult: 1, encounterMult: 0, label: 'mountains' },
  // Town cosmetics — neutral mechanics, no encounter weight; `town_wall` blocks
  // movement. (Town / local-room grids don't roll encounters anyway.)
  cobblestone: { passable: true, travelMult: 1, encounterMult: 0, label: 'cobblestone' },
  garden: { passable: true, travelMult: 1, encounterMult: 0, label: 'garden' },
  town_wall: { passable: false, travelMult: 1, encounterMult: 0, label: 'town wall' },
};

// ─── Terrain ART (campaign-scoped skin over the global tile set) ──────
//
// The base art is one hand-painted tileset (David Baumgart, 8 overland
// PNGs under /art/tiles). The tile CATALOG below adds recolored variants:
// each entry names a base PNG plus an optional CSS filter the renderer
// applies — so alternate looks (ashlands, frostbound) cost no new assets.
//
// A campaign's `terrainArt` section maps terrain TYPE → tile id from this
// catalog; unmapped types render their default tile. Shared so the FE
// renders it and the BE validates it from one definition. PURELY VISUAL —
// mechanics stay on the terrain type (see `TERRAIN`), whatever it looks like.
export interface TerrainTileSpec {
  // The PNG this tile draws: /art/tiles/<base>.png (the 8 shipped tiles).
  base: 'plains' | 'road' | 'forest' | 'hills' | 'swamp' | 'snow' | 'water' | 'mountain';
  label: string;
  // CSS filter recoloring the base PNG; omitted = the art as painted.
  filter?: string;
}

export const TERRAIN_TILES = {
  // The base set — each overland type's own tile, unfiltered.
  plains: { base: 'plains', label: 'plains' },
  road: { base: 'road', label: 'road' },
  forest: { base: 'forest', label: 'forest' },
  hills: { base: 'hills', label: 'hills' },
  swamp: { base: 'swamp', label: 'swamp' },
  snow: { base: 'snow', label: 'snow' },
  water: { base: 'water', label: 'water' },
  mountain: { base: 'mountain', label: 'mountains' },
  // Ashlands — scorched, grey, post-cataclysm.
  'plains-ash': { base: 'plains', label: 'ash flats', filter: 'grayscale(0.75) brightness(0.7)' },
  'road-cracked': {
    base: 'road',
    label: 'cracked road',
    filter: 'grayscale(0.55) brightness(0.8)',
  },
  'forest-dead': {
    base: 'forest',
    label: 'dead forest',
    filter: 'sepia(0.55) saturate(0.45) brightness(0.72)',
  },
  'hills-barren': {
    base: 'hills',
    label: 'barren hills',
    filter: 'saturate(0.35) brightness(0.78)',
  },
  'swamp-blight': {
    base: 'swamp',
    label: 'blighted mire',
    filter: 'hue-rotate(28deg) saturate(0.7) brightness(0.7)',
  },
  'water-murk': {
    base: 'water',
    label: 'murkwater',
    filter: 'hue-rotate(45deg) saturate(0.5) brightness(0.55)',
  },
  'mountain-char': {
    base: 'mountain',
    label: 'charred peaks',
    filter: 'grayscale(0.6) brightness(0.6)',
  },
  'snow-ashfall': { base: 'snow', label: 'ashfall', filter: 'grayscale(0.9) brightness(0.75)' },
  // Frostbound — washed-out, icy.
  'plains-tundra': {
    base: 'plains',
    label: 'tundra',
    filter: 'saturate(0.5) brightness(1.15) hue-rotate(-12deg)',
  },
  'road-snowbound': {
    base: 'road',
    label: 'snowbound road',
    filter: 'saturate(0.55) brightness(1.18)',
  },
  'forest-frost': {
    base: 'forest',
    label: 'frosted forest',
    filter: 'saturate(0.45) brightness(1.2) hue-rotate(-18deg)',
  },
  'hills-frost': {
    base: 'hills',
    label: 'frosted hills',
    filter: 'saturate(0.4) brightness(1.25)',
  },
  'swamp-frozen': {
    base: 'swamp',
    label: 'frozen fen',
    filter: 'saturate(0.45) brightness(1.15) hue-rotate(-25deg)',
  },
  'water-ice': { base: 'water', label: 'pack ice', filter: 'saturate(0.45) brightness(1.4)' },
} as const satisfies Record<string, TerrainTileSpec>;

export type TerrainTileId = keyof typeof TERRAIN_TILES;

// A campaign's terrain-art overrides: type → tile id. Empty / absent =
// every type renders its default tile.
export type TerrainArtMap = Partial<Record<TerrainType, TerrainTileId>>;

/**
 * Which combat side an entity fights for: PCs and their allies
 * (companions, summons) oppose enemies. Derived from `isEnemy` /
 * `isCompanion` when an entity's `side` is unset — see `entitySide()`.
 */
export type EntitySide = 'pc' | 'enemy' | 'ally';

export interface CombatEntity {
  id: string; // character.id for PCs, enemy instance id for enemies, owner.id + ':companion' for animal companions
  isEnemy: boolean;
  /**
   * Combat side (RE-1 Phase 4). Optional + back-compat: when unset,
   * derived from `isEnemy` / `isCompanion` via `entitySide()`. Summons
   * and companions set this to `'ally'` explicitly as Phase 4 lands.
   */
  side?: EntitySide;
  pos: GridPos;
  /**
   * Current HP.
   * - **Enemies (`isEnemy: true`):** authoritative; the engine mutates
   *   this directly when an enemy takes damage.
   * - **PCs (`isEnemy: false`):** mirror of `characters[].hp`. Writes
   *   MUST route through `commitCharacter(st, char)` (BE) so the
   *   characters[] entry and this mirror stay in sync. Reads from this
   *   field are safe; if you suspect drift, prefer reading
   *   `characters[].hp` by id.
   */
  hp: number;
  maxHp: number;
  /**
   * Active conditions. Same mirror policy as `hp` — for PCs, source
   * of truth is `characters[].conditions`; route writes through
   * `commitCharacter`.
   */
  conditions: string[];
  condition_durations: Record<string, number>;
  // Ally combatant fields (companions / summons). `isCompanion` marks an
  // ally tied to an owner PC; the stat-block fields below (ac/toHit/damage)
  // drive its attacks. (Beast Master itself is PHB-only / out of scope;
  // these fields serve SRD summons such as Animate Dead — RE-1 Phase 4.)
  isCompanion?: boolean;
  companionOwnerId?: string; // character.id of the Ranger this companion belongs to
  companionName?: string; // display name (e.g. 'Wolf')
  ac?: number; // companion AC (PCs use character.ac, enemies use Enemy.ac)
  toHit?: number; // companion attack bonus
  damage?: string; // companion damage dice expression (e.g. '2d4+2')
  // RE-1 Phase 4 — summon lifecycle. `summoned_by` is the summoning
  // caster's character id; `summon_concentration` marks summons that
  // vanish when that caster's concentration drops (e.g. Conjure Animals),
  // as opposed to persistent ones (e.g. Find Familiar).
  summoned_by?: string;
  summon_concentration?: boolean;
  // SRD Find Familiar — a non-combatant ally that "can't take the Attack action"
  // but acts on its turn. `runAllyTurn` skips the attack and instead takes the
  // Help action, granting its owner Advantage on their next attack
  // (`help_target_id`). A scouting/aid companion, not an attacker.
  noAttack?: boolean;
  // RAW player-command (e.g. Animate Dead): the enemy entity id this summon
  // has been ordered to attack. `selectTarget`/`runAllyTurn` prefer it while
  // that enemy lives, else fall back to the AI-default nearest enemy. Set by
  // the owner's `command_summon` bonus action. (RE-1 Phase 4.5.)
  commanded_target_id?: string;
  // SRD 5.2.1 Mounted Combat — a rider/mount pair binds these two ids: the
  // rider entity carries `mount_id` (the creature it rides), and the mount
  // entity carries `rider_id` (its rider). A ridden controlled mount shares
  // the rider's space (same `pos`) and gets no independent turn — it moves on
  // the rider's turn. `speed_ft` is the mount's own Speed, used as the rider's
  // movement budget while mounted (Phantom Steed = 100 ft).
  mount_id?: string;
  rider_id?: string;
  speed_ft?: number;
  // SRD 5.2.1 — when grappled, records the id of the grappler so we can end the
  // condition if the grappler dies/is incapacitated, and so the contested escape
  // check has a target's mod to roll against.
  grappled_by?: string;
  // Fixed escape DC for a monster's grapple-on-hit (e.g. Griffon Rend, escape
  // DC 14). When set, `try_escape_grapple` rolls against this DC instead of a
  // contested check vs the grappler. Stamped by the enemy attack's auto-apply
  // onHitEffect path; cleared alongside `grappled_by` on escape/incapacitation.
  grapple_escape_dc?: number;
  // SRD enemy reaction economy — set when a monster spends its one reaction
  // this round (e.g. Bandit Captain Parry). Refreshed (cleared) on round wrap,
  // mirroring "you regain your reaction at the start of each of your turns".
  reaction_used?: boolean;
  // SRD Gnoll Rampage (1/Day) — set once the creature has taken its bonus Rampage
  // attack this encounter. Unlike `reaction_used` this is NOT refreshed on round
  // wrap (1/day ≈ once per combat); it clears only when entities are re-seeded.
  rampage_used?: boolean;
  // SRD recharge attack (a dragon's Fire Breath) — the charge state for this
  // entity's `breathWeapon`. `undefined` ⇒ available (fresh combat / re-seed);
  // `false` ⇒ spent, re-rolled at the start of each of the creature's turns
  // (recharge on a d6 ≥ the weapon's `rechargeMin`). Set `false` when fired.
  breath_charged?: boolean;
  // SRD Vision & Light — bright-light radius (ft) this entity sheds as a light
  // source (the Light cantrip / a torch on a PC, Daylight, etc.). A cell within
  // this radius is brightly lit, and within 2× it is at least dimly lit — either
  // way a creature there is illuminated and can be SEEN in a dark room, dodging
  // the darkness blind-combat penalties. 0/undefined = not a light source. Set
  // by the Light/Daylight cast paths; read via `isIlluminated`.
  light_radius_ft?: number;
  // SRD Vision & Light — the spell level of the effect that made this a light
  // source (Light cantrip = 0, Daylight = 3). Drives the RAW dispel cutoffs:
  // the Darkness spell (L2) snuffs overlapping light created by a spell of level
  // 2 or lower (so Light, not Daylight), and Daylight (L3) banishes overlapping
  // Darkness (L2 ≤ 3). Undefined when not spell-made (e.g. a mundane torch).
  light_spell_level?: number;
  // SRD Charmed (enemy charmed by a PC, e.g. Charm Person/Monster) — the
  // charmer's character id. A Charmed creature can't attack its charmer, so
  // `selectTarget` drops the charmer from this enemy's candidate targets.
  charmer_id?: string;
  // SRD Frightened (enemy frightened by a PC, e.g. Fear) — the fear source's
  // character id. A Frightened creature attacks with Disadvantage and can't
  // willingly move closer to the source while it can see it; the enemy turn
  // loop reads this for both (LoS approximated as "always in sight").
  frightened_by?: string;
  // Boss-phase tracking. Counts how many phases the boss has entered. The
  // engine re-applies effects 0..phase_index-1 on every takeAction so the
  // seed's runtime Enemy fields reflect the current phase. A 0 (or undefined)
  // means the boss is still in its base statline.
  phase_index?: number;
  // SRD Polymorph state — when set, the entity is transformed
  // into a beast form. The form's HP pool lives on `temp_hp` (per
  // SRD Polymorph rewrite: form HP is Temporary Hit Points, not
  // a separate buffer). Damage absorbs into temp_hp first; when
  // temp_hp depletes to 0 the form drops automatically (entity stays
  // at its real `hp`, condition cleared, polymorph_state cleared).
  // Healing spells can't restore the form's HP — temp HP can't be
  // healed in 5e, so the 2014 heal exploit is structurally blocked.
  polymorph_state?: {
    formName: string;
  };
  // SRD temporary hit points (enemies only — PC temp HP lives
  // on `Character.temp_hp`). Damage absorbs into this before `hp`;
  // when depleted, the polymorph form drops (if `polymorph_state`
  // is set) and excess damage carries over to `hp` (per RAW).
  temp_hp?: number;
  // SRD Confusion — set once the creature has taken a full turn while
  // `confused`. RAW re-saves at the END of each turn, so a creature is
  // confused for at least its first turn; the enemy loop skips the re-save
  // on that first turn (this flag false/undefined) and rolls it at the
  // start of each subsequent turn (flag true) — functionally identical to
  // the end-of-turn save, since nothing affects the creature in between.
  // Reset when the `confused` condition is (re)applied or cleared.
  confused_acted?: boolean;
  // SRD "save ends" conditions on an enemy (Power Word Stun's Stunned, Slow's
  // slowed): the creature repeats a saving throw at the end of each of its
  // turns, ending the condition on a success. Maps the condition to the ability
  // + DC of that recurring save. The enemy turn loop evaluates these at the
  // start of each turn (modelling the prior turn's end, like `confused_acted`);
  // a success removes the condition and its entry here. Stamped on cast by the
  // save / AoE-condition paths (for `spell.conditionSaveEnds` spells) or by a
  // bespoke handler (Power Word Stun). The DC is the caster's spell save DC.
  // The optional `recurDice` / `recurType` / `casterId` carry a recurring damage
  // tick (Phantasmal Killer 4d10, Phantasmal Force 2d8): on each FAILED end-of-
  // turn save the creature takes `recurDice` damage of `recurType`, credited to
  // `casterId` on a kill. Absent ⇒ a pure save-ends condition (Slow, Stun).
  save_ends?: Record<
    string,
    {
      ability: AbilityKey;
      dc: number;
      recurDice?: string;
      recurType?: string;
      casterId?: string;
      // Source phrase for the recurring-damage line ("takes 3 fire from {label}").
      // Defaults to "the illusion" (Phantasmal Killer / Force); Alchemist's Fire
      // sets "the flames".
      label?: string;
    }
  >;
  // Conditions in `save_ends` for which this creature has completed ≥1 afflicted
  // turn — gates the recurring save so the effect always lasts at least its
  // first turn (RAW), mirroring `confused_acted` but per-condition.
  save_ends_acted?: string[];
}

// ─── Structured actions ──────────────────────────────────────────────

export type StructuredAction =
  | { type: 'attack'; targetEnemyId?: string }
  // `lootKey` selects which placed item to take (a room may hold several);
  // omitted → the first available item in the room.
  | { type: 'loot'; lootKey?: string }
  // Walk the party marker to a cell adjacent to `pos` (out of combat). Dispatched
  // by clicking a loot / object token on the local-room map; the contextual
  // Pick-up / Interact choice then surfaces via its adjacency gate.
  | { type: 'approach'; pos: GridPos }
  | { type: 'use'; itemId: string; targetCharId?: string }
  | { type: 'throw_item'; itemId: string; targetEnemyId: string }
  | { type: 'sneak' }
  | { type: 'examine' }
  | { type: 'death_save' }
  | { type: 'pass' }
  | { type: 'end_turn' }
  | { type: 'short_rest' }
  | { type: 'long_rest' }
  // Wizard Arcane Recovery / Land Druid Natural Recovery — recover expended
  // spell slots up to the feature's budget; `plan` is the chosen allocation id
  // (omitted → the engine's default lowest-first plan).
  | { type: 'recover_slots'; recovery: 'arcane' | 'natural'; plan?: string }
  // `npcId` selects which NPC in the room (a room may host several).
  | { type: 'talk'; npcId: string }
  // `responseIdx` is relative to the conversation's CURRENT node (resolved via
  // `GameState.active_conversation.path`).
  | { type: 'talk_response'; responseIdx: number }
  // Conversation navigation: step up a nested dialogue level / leave entirely.
  | { type: 'conversation_back' }
  | { type: 'end_conversation' }
  // Dismiss the post-combat "Continue" gate and return to exploration (combat
  // no longer auto-switches straight back to the out-of-combat view).
  | { type: 'continue' }
  | { type: 'buy'; itemId: string; price: number }
  // Vendor pane: open / close the NPC's wares (a sub-state nested under the
  // active conversation, like a nested dialogue branch). See active_shop.
  | { type: 'enter_shop' }
  | { type: 'exit_shop' }
  // Leveling pane: open the level-up cascade for one party member (out of
  // combat) / step back to the roster. See active_leveling.
  | { type: 'enter_leveling'; characterId: string }
  | { type: 'exit_leveling' }
  | { type: 'attack_npc'; npcId: string }
  | { type: 'use_class_feature'; featureId: string; targetEnemyId?: string }
  | { type: 'apply_asi'; stat: AbilityKey }
  | {
      // Take a feat. When the feat is a half-feat with `choices`,
      // `abilityChoice` records the player's pick. When the feat has
      // a `save-proficiency` effect with empty abilities, the chosen
      // abilities are recorded on Character.feat_choices. For Magic
      // Initiate (`extra-cantrips-and-l1`), the player picks 2 cantrip
      // ids + 1 L1 spell id from the matching list; the engine adds
      // them to `spells_known` and tracks the L1 free-cast token on
      // `class_resource_uses.magic_initiate_l1_used`.
      type: 'take_feat';
      featId: string;
      abilityChoice?: AbilityKey;
      cantripChoices?: string[];
      l1Choice?: string;
    }
  | { type: 'de_attune'; instanceId: string }
  | {
      // SRD Influence action — distinct from `talk` (free narrative
      // dialogue). Triggers a CHA-based skill check to change an NPC's
      // mind or coerce an enemy mid-combat. In combat: consumes the
      // Action (no attack that turn). Out of combat: no action cost
      // (the narrative time investment is the cost). DC = max(15, target's
      // INT score). Exactly one of `targetNpcId` / `targetEnemyId` is
      // expected.
      type: 'influence';
      skill: 'persuasion' | 'deception' | 'intimidation';
      targetNpcId?: string;
      targetEnemyId?: string;
    }
  | {
      // SRD Study action — INT-based mental deduction. Distinct
      // from the legacy `examine` action (which never had formal
      // combat-action status). Lets a player roll INT + skill prof
      // to identify a creature's vulnerabilities / immunities,
      // analyze an object's mechanism, or recall lore. In combat:
      // costs the Action (no attack on a Study turn). Out of combat:
      // no action cost. DC: 15 base for general lore; tuned to CR
      // for creature analysis.
      type: 'study';
      skill: 'arcana' | 'history' | 'investigation' | 'nature' | 'religion';
      targetEnemyId?: string;
      // Free-form lore prompt; reserved for future loremaster flows.
      // The current handler covers creature-analysis only; lore +
      // object branches are TODO.
      loreTopic?: string;
    }
  | {
      type: 'cast_spell';
      spellId: string;
      slotLevel: number;
      ritual?: boolean;
      targetEnemyId?: string;
      // SRD multi-target spells (Magic Missile darts, Eldritch Blast
      // beams). One entry per dart/beam; duplicates = multiple darts on the
      // same target. When omitted, falls back to focus-fire on `targetEnemyId`.
      targetEnemyIds?: string[];
      // Ally / party-member target. Two consumers:
      //   - Buff spells (Heroism, Aid, Greater Invisibility, Fly,
      //     Levitate, ...): FE picks which living party member
      //     receives the buff. Omitted = caster targets self.
      //   - Revive spells (Revivify, Raise Dead, ...): the *dead*
      //     party member to be restored. Required for revive spells;
      //     the handler errors out when missing.
      targetCharId?: string;
      // Multi-target ally buff (Bless): the party members the caster chooses to
      // affect (up to 3, +1 per slot above the spell's base). Omitted = the
      // backend auto-picks (caster + nearest allies). The FE collects these via
      // the target picker (GameChoice.pickTargets). Enemy multi-target debuffs
      // (Bane) reuse `targetEnemyIds` above.
      targetCharIds?: string[];
      // Summon spells (Animate Dead): which creature variant to raise
      // (e.g. 'Skeleton' or 'Zombie'). Omitted = the spell's base block.
      // (RE-1 Phase 4.5.)
      summonVariant?: string;
      // Polymorph — the chosen beast form id (BEAST_FORMS). Omitted = auto-Wolf.
      beastForm?: string;
      // Greater Restoration — the single effect to remove (option picker):
      // 'exhaustion' | 'charmed' | 'petrified' | 'hp_max'. Omitted = default bundle.
      restorationEffect?: string;
      // Protection from Energy — the chosen damage type to resist (option
      // picker): 'acid' | 'cold' | 'fire' | 'lightning' | 'thunder'. Omitted =
      // the spell's default (fire).
      resistType?: string;
      // Dragon's Breath — the chosen breath damage type (option picker): 'acid'
      // | 'cold' | 'fire' | 'lightning' | 'poison'. Omitted = fire.
      breathType?: string;
      // Blindness/Deafness — the chosen condition (option picker): 'blinded' |
      // 'deafened'. Honored only if in the spell's `conditionChoices`; else the
      // spell's default `condition` (Blinded).
      conditionChoice?: ConditionName;
      // SRD Wish (basic use) — the spell id (level 1-8) to duplicate. Set by the
      // Wish option picker; the handler re-dispatches it as a free duplicate.
      wishSpellId?: string;
      // Marks a cast that IS a free Wish duplicate (no slot / prep / material /
      // level prerequisites) — set by the Wish handler on the re-dispatched cast.
      wishDuplicate?: boolean;
      // Cleric L10 Divine Intervention — cast this Cleric spell (level ≤5,
      // non-Reaction) without a slot or Material components, 1/Long Rest.
      // Set by the Divine Intervention choice surface; precast validates
      // eligibility and bypasses the prep/slot/material gates.
      divineIntervention?: boolean;
      // Evoker L14 Overchannel — maximize this damaging spell's dice (level
      // 1-5 slot). First use/long rest is free; later uses deal escalating
      // Necrotic self-damage. Validated in precast.
      overchannel?: boolean;
      // Warlock Mystic Arcanum (L11/13/15/17) — cast this chosen L6-9 spell
      // once per long rest without a slot. Validated in precast.
      mysticArcanum?: boolean;
    }
  | { type: 'disarm_trap' }
  | { type: 'interact_object'; objectId: string }
  | { type: 'two_weapon_attack'; targetEnemyId?: string }
  // Land Druid L3 — Land's Aid: bonus action (2 uses/long rest)
  // that heals an ally OR damages an enemy. Picks one of three
  // variants at use time.
  | {
      type: 'use_lands_aid';
      variant: 'heal' | 'harm_necrotic' | 'harm_radiant';
      targetCharId?: string;
      targetEnemyId?: string;
    }
  | { type: 'attune'; instanceId: string }
  | { type: 'grapple'; targetEnemyId?: string }
  | { type: 'try_escape_grapple' }
  | { type: 'stand_up' }
  | { type: 'spend_inspiration' }
  // Manual level-up into a specific class (SRD multiclassing).
  // Bumps `char.level` + `class_levels[className]` together. Validates
  // XP threshold; for non-primary classes also validates the SRD
  // multiclass prerequisites (ability-score minimums). Surfaces as a
  // choice when XP crosses the next-level threshold. Out-of-combat
  // only (RAW: level-ups happen during downtime / long rest).
  | { type: 'level_up_class'; className: string }
  | { type: 'shove'; targetEnemyId?: string }
  | { type: 'dodge' }
  | { type: 'disengage' }
  // SRD 5.2.1 Hide [Action] — the general action available to any class
  // (Rogues also get it as a Bonus Action via Cunning Action).
  | { type: 'hide' }
  | { type: 'grid_move'; entityId: string; to: GridPos }
  // SRD 5.2.1 Mounted Combat — climb onto a willing mount within 5 ft, or get
  // off the one you're riding. Each costs half your Speed of movement.
  | { type: 'mount'; mountId: string }
  | { type: 'dismount' }
  // RE-4 — reposition a persistent damage zone (Flaming Sphere roll, Moonbeam /
  // Call Lightning re-aim) onto a cell within the spell's move range.
  | { type: 'move_zone'; zoneId: string; to: GridPos }
  // RE-4 — re-issue a recurring spell attack (Spiritual Weapon / Vampiric Touch)
  // at a target on a later turn, for the spell's recurring cost.
  | { type: 'recurring_spell_attack'; targetEnemyId?: string }
  // SRD Dragon's Breath — the granted-breath holder exhales a 15-ft cone toward
  // the aimed enemy (its action). Surfaced while `Character.granted_breath` is set.
  | { type: 'use_breath'; targetEnemyId?: string }
  | { type: 'jump'; to: GridPos } // SRD Long Jump — leap up to STR ft over terrain/obstacles
  // 3-level grid map model — move the single party marker on the current grid
  // (regional / town / local-exploration). Free pathfind out of combat; the
  // regional grid additionally spends travel time + rolls encounters per square.
  // Arriving on a transition cell (site / venue / room exit) resolves it
  // (descend / ascend / change room).
  | { type: 'marker_move'; to: GridPos }
  // SRD Travel Pace — set the party's overland stance (regional map, free).
  | { type: 'set_pace'; pace: 'fast' | 'normal' | 'slow' }
  // Town teleportation (Teleport / Teleportation Circle interstitial).
  | { type: 'teleport_to'; townId: string }
  | { type: 'cancel_teleport' }
  | { type: 'accept_quest'; questId: string }
  | { type: 'complete_quest'; questId: string }
  | { type: 'dash' }
  | { type: 'help'; targetId: string }
  | { type: 'ready'; trigger: string; action: StructuredAction }
  | { type: 'use_reaction' }
  // SRD 5.2.1 Haste — wrapper for the spell's additional action. The
  // inner action runs in a context where the standard action_used
  // gate is bypassed (the spell gives a free second action slot
  // restricted to Attack / Dash / Disengage / Hide / Utilize).
  // Setting `haste_extra_action_used = true` marks the slot consumed
  // so the choice generator stops surfacing the Haste menu.
  | {
      type: 'haste_extra_action';
      inner:
        | { type: 'attack'; targetEnemyId?: string }
        | { type: 'dash' }
        | { type: 'disengage' }
        | { type: 'sneak' }
        | { type: 'interact_object'; objectId: string };
    }
  | { type: 'select_subclass'; subclass: string }
  // SRD 5.2.1 Fighting Style feat pick, granted by class features (Fighter
  // L1/L7, Paladin/Ranger L2). Out-of-combat, no action cost. (RE-2.)
  | { type: 'choose_fighting_style'; style: string }
  // SRD 5.2.1 Expertise pick (Rogue L1/L6, Bard L2/L9): double proficiency in a
  // chosen skill proficiency. `skill` matches a `skill_proficiencies` entry.
  // Out-of-combat, no action cost. (RE-2.)
  | { type: 'choose_expertise'; skill: string }
  // 2024 Weapon Mastery slot growth — on level-up the player picks a new weapon
  // to master (Fighter L4/10/16, Barbarian L4/10). `weaponId` is the chosen
  // weapon. Out-of-combat, no action cost.
  | { type: 'choose_weapon_mastery'; weaponId: string }
  // SRD 5.2.1 Ranger Hunter "feature option" pick (Hunter's Prey L3, Defensive
  // Tactics L7): choose one of two options, swappable on a rest. Out-of-combat,
  // no action cost. (RE-2.)
  | { type: 'choose_hunter_option'; feature: 'hunters_prey' | 'defensive_tactics'; option: string }
  // SRD 5.2.1 Sorcerer Metamagic option pick (learn one of the options; 2/4/6
  // known at sorcerer L2/10/17). Out-of-combat, no action cost. (RE-2.)
  | { type: 'choose_metamagic'; option: string }
  // SRD 5.2.1 Draconic Sorcery Elemental Affinity (L6): choose the affinity
  // damage type (acid/cold/fire/lightning/poison). Out-of-combat. (RE-2.)
  | {
      type: 'choose_elemental_affinity';
      damageType: 'acid' | 'cold' | 'fire' | 'lightning' | 'poison';
    }
  // SRD 5.2.1 Cleric Blessed Strikes (L7): choose Divine Strike or Potent
  // Spellcasting. Out-of-combat, no action cost. (RE-2.)
  | { type: 'choose_blessed_strikes'; option: 'divine_strike' | 'potent_spellcasting' }
  // SRD 5.2.1 Cleric Divine Order (L1): choose Protector (Martial + Heavy
  // training) or Thaumaturge (extra Cleric cantrip via `cantrip` + WIS to
  // Arcana/Religion). Out-of-combat, no action cost. (RE-2.)
  | { type: 'choose_divine_order'; option: 'protector' | 'thaumaturge'; cantrip?: string }
  // SRD 5.2.1 Wizard Spell Mastery (L18): designate a L1 (tier 1) or L2
  // (tier 2) action spell to cast at will with no slot. Out-of-combat. (RE-2.)
  | { type: 'choose_spell_mastery'; tier: 1 | 2; spellId: string }
  // SRD 5.2.1 Wizard Signature Spells (L20): designate a L3 spell as a
  // signature spell (free L3 cast, 1/short-or-long rest). Out-of-combat. (RE-2.)
  | { type: 'choose_signature_spell'; spellId: string }
  // SRD 5.2.1 Evoker Evocation Savant (L3): add a free Wizard Evocation spell
  // to the spellbook (budget: 2 + one per new slot level). Out-of-combat. (RE-2.)
  | { type: 'choose_evocation_savant'; spellId: string }
  // SRD 5.2.1 Wizard Memorize Spell (L5): on a short rest, replace one prepared
  // level-1+ spell (`swapOut`) with another from the spellbook (`swapIn`). (RE-2.)
  | { type: 'memorize_spell'; swapOut: string; swapIn: string }
  // SRD 5.2.1 Fiend Warlock Fiendish Resilience (L10): choose a damage type
  // (not Force) to gain Resistance to until re-chosen. Out-of-combat. (RE-2.)
  | { type: 'choose_fiendish_resilience'; damageType: string }
  // SRD 5.2.1 Warlock Mystic Arcanum (L11/13/15/17): designate a L6-9 spell as
  // the arcanum for its tier (free 1/long-rest cast). Out-of-combat. (RE-2.)
  | { type: 'choose_mystic_arcanum'; spellId: string }
  // SRD 5.2.1 Paladin Lay on Hands (L1): bonus-action touch heal drawing from
  // a pool of 5 × Paladin level HP. `targetCharId` is the healed party member
  // (may be the paladin). (RE-2.)
  | { type: 'lay_on_hands'; targetCharId: string }
  | { type: 'prepare_spells'; spellIds: string[] }
  | { type: 'resolve_reaction'; accept: boolean; source?: 'inspiration' | 'stroke_of_luck' }
  // RAW player-command for a summoned creature (Animate Dead, etc.). On the
  // owner's turn, spend a bonus action to direct one summon's target for its
  // upcoming turn. Records `commanded_target_id` on the summon entity; the
  // ally-turn AI prefers it while the target lives. (RE-1 Phase 4.5.)
  | { type: 'command_summon'; summonId: string; targetEnemyId: string }
  // BE-internal (never sent by the FE): one enemy sub-attack against a PC,
  // dispatched with an `enemyActor` so the enemy turn runs through the same
  // dispatcher as PC actions. `advIdx` / `multiattackIdx` feed the
  // reaction-window resume coords. (EE-2 — dispatcher-integrated enemy turns.)
  | { type: 'enemy_attack'; targetCharId: string; advIdx: number; multiattackIdx: number }
  // BE-internal: an enemy damage spell resolving against a PC (after the
  // Counterspell window, handled by the orchestrator). Dispatched with an
  // `enemyActor`. (EE-3 — dispatcher-integrated enemy spellcasting.)
  | { type: 'enemy_cast'; spellId: string; targetCharId: string }
  // BE-internal: an enemy's approach/move step toward a PC before its attack
  // (path-plan + opportunity attacks + position commit). Dispatched with an
  // `enemyActor`. `resumeMi` skips the move mid-multiattack. (EE-4.)
  | { type: 'enemy_move'; targetCharId: string; resumeMi: number }
  // Out-of-combat only: switch which PC is the "lead" / active character
  // for subsequent narrative attribution + skill checks. RAW has no
  // notion of initiative outside combat — the party operates as a unit
  // — so the player picks whose voice drives the next interaction.
  // No-op in combat: initiative is driven by the initiative_order.
  | { type: 'set_active_character'; characterId: string };

// ─── Choice metadata (drives FE rendering) ───────────────────────────

// Compass direction tag for grid movement choices — drives the 3x3 D-pad
// on the frontend so it can place each arrow in the right cell.
export type ChoiceDirection = 'N' | 'NE' | 'E' | 'SE' | 'S' | 'SW' | 'W' | 'NW';

// Semantic kind hint for the frontend. Optional: untagged choices fall back
// to the plain text-button rendering. The frontend uses `kind` to route
// choices to specialised renderers (D-pad for grid_move, icon row for the
// default-action universals). New kinds can be added incrementally.
export type ChoiceKind =
  | 'grid_move'
  | 'move_zone'
  | 'recurring_spell_attack'
  | 'use_breath'
  | 'dash'
  | 'disengage'
  | 'dodge'
  | 'hide'
  | 'ready'
  | 'attack'
  | 'grapple'
  | 'shove'
  // SRD 5.2.1 Mounted Combat — Mount / Dismount movement options.
  | 'mount'
  | 'two_weapon_attack'
  | 'use_lands_aid'
  | 'cast_spell'
  | 'class_feature'
  // Dialogue choices while a conversation is active (NPC responses, Back, End
  // conversation). The frontend routes these to the dedicated ConversationPanel.
  | 'conversation'
  // Vendor-pane choices (buy rows + the Back control). The frontend renders
  // these in the dedicated VendorPanel instead of the normal choice list.
  | 'vendor'
  // Leveling-pane choices (the per-member roster entries, the class/ASI/mastery
  // cascade, and Back). Rendered in the dedicated LevelingPanel.
  | 'leveling'
  // The post-combat "Continue" gate. The frontend renders a dedicated
  // interstitial instead of listing it among the normal choices.
  | 'continue';

export interface GameChoice {
  label: string;
  action: StructuredAction;
  requiresBonusAction?: boolean;
  // Optional UI hint. Frontend uses `kind` to pick a renderer (e.g. D-pad
  // for grid_move) and falls back to the standard button list otherwise.
  kind?: ChoiceKind;
  // For kind === 'grid_move': the cardinal/ordinal direction of the move.
  direction?: ChoiceDirection;
  // Hint for the grid renderer: when this is a cast_spell choice for an AoE
  // spell, lets the frontend tint the affected cells on hover without needing
  // the spell catalog or per-shape geometry.
  aoePreview?: {
    shape: 'sphere' | 'cone' | 'cube' | 'line';
    radiusFt: number;
    targetEnemyId?: string;
    rangeKind?: 'self' | 'touch' | 'ranged';
  };
  // Stable key for "this choice has already been used this adventure."
  // When set and the key appears in GameState.seen_choices, the FE dims
  // the button. The backend disambiguates by room / npc / object instance
  // so e.g. two different "Inspect Dirty Chest" objects get distinct keys.
  // Absent on choices that don't benefit from dimming (movement, combat).
  seenKey?: string;
  // Optional UI hint: this choice opens a target picker before it is sent.
  // The FE collects 1..`max` targets of the given side and re-sends the action
  // with `targetCharIds` (ally) / `targetEnemyIds` (enemy) populated; the
  // backend validates the chosen targets and falls back to its auto-pick when
  // they're absent. Used by Bless (ally) — Bane (enemy) and others follow.
  pickTargets?: {
    side: 'ally' | 'enemy';
    max: number;
  };
  // Optional UI hint: this choice opens a single-select OPTION picker before it
  // is sent — Polymorph's beast form, Greater Restoration's effect. The FE shows
  // `options`, and on confirm sets `action[param]` to the chosen id and re-sends
  // (the backend honors it, falling back to its default when absent).
  pickOption?: {
    param: string;
    title: string;
    options: { id: string; label: string; sub?: string }[];
  };
}

// ─── Combat-log events (parallel to prose narrative) ─────────────────

export const COMBAT_LOG_MAX = 30;

export type CombatEvent =
  | {
      kind: 'attack_hit';
      attackerId: string;
      attackerName: string;
      targetId: string;
      targetName: string;
      damage: number;
      damageType: string;
      isCrit: boolean;
      toHit: number;
      targetAc: number;
      round: number;
    }
  | {
      kind: 'attack_miss';
      attackerId: string;
      attackerName: string;
      targetId: string;
      targetName: string;
      toHit: number;
      targetAc: number;
      round: number;
    }
  | {
      kind: 'kill';
      attackerId: string;
      attackerName: string;
      victimId: string;
      victimName: string;
      xp: number;
      round: number;
    }
  | {
      kind: 'condition_applied';
      targetId: string;
      targetName: string;
      condition: string;
      source: string;
      round: number;
    }
  | {
      kind: 'save';
      characterId: string;
      characterName: string;
      ability: string;
      roll: number;
      dc: number;
      success: boolean;
      vs: string;
      round: number;
    }
  | {
      kind: 'phase_transition';
      bossId: string;
      bossName: string;
      phaseName: string;
      narrative: string;
      round: number;
    };

// ─── Game-engine consequence type (campaign rules + quest rewards) ───

export type GameConsequence =
  | { type: 'add_narrative'; text: string }
  | { type: 'set_flag'; key: string; value: boolean | string | number }
  | { type: 'give_item'; itemId: string; characterId?: string }
  | { type: 'modify_hp'; amount: number; characterId?: string }
  | { type: 'unlock_room'; roomId: string }
  | { type: 'spawn_enemy'; roomId: string; enemyId: string }
  | { type: 'set_escape' }
  | { type: 'advance_quest'; questId: string; stepId: string }
  // Activate a quest by id (no-op if already started or completed; unknown
  // ids warn and skip). The explicit "this conversation starts the quest"
  // trigger — clearer to author than the set_flag + step-condition indirection.
  | { type: 'start_quest'; questId: string }
  | { type: 'set_faction_rep'; factionId: string; delta: number }
  | { type: 'travel_to'; locationId: string }
  | { type: 'give_gold'; amount: number }
  // Split `amount` XP evenly across all living party members (rounded
  // down). Used for quest completion so the engine can level up the
  // party at milestones rather than only through enemy kills.
  | { type: 'give_xp'; amount: number }
  | { type: 'set_npc_attitude'; npcId: string; attitude: NpcAttitude }
  // Remove one instance of itemId from the party's inventory (any
  // member who carries it). Used for quest turn-ins like the Guild
  // Ledger — when the player hands over a quest item, it should leave
  // their pack.
  | { type: 'consume_item'; itemId: string };

// ─── Room objects + NPCs ─────────────────────────────────────────────

export interface RoomObject {
  id: string;
  name: string;
  desc: string;
  interactText: string;
  searchable?: boolean;
  searchDC?: number;
  lootIds?: string[];
  foundText?: string;
  emptyText?: string;
  // Grid cell for the object on the local-room map. When set, the object
  // renders as a clickable map token; clicking walks the party adjacent
  // (the `approach` action) and the "Interact" choice is gated on adjacency.
  // Unset → object stays text-only (legacy behaviour).
  pos?: GridPos;
}

export interface NpcShopEntry {
  itemId: string;
  price: number;
}

export interface NpcTemplate {
  id: string;
  name: string;
  attitude: NpcAttitude;
  // Treat `name` as a proper noun in combat prose (no definite article) when
  // this NPC turns hostile and is fought. Omitted ⇒ inferred from the name's
  // shape; set for single-word proper names a heuristic can't catch (e.g.
  // "Dusk"). Mirrors Enemy.proper_noun, carried through npcAsEnemy.
  proper_noun?: boolean;
  // Stat block — used when attitude becomes hostile or player attacks
  hp: number;
  ac: number;
  damage: string;
  toHit: number;
  xp: number;
  dex?: number;
  // Position on the room's local grid. When set, the NPC renders as a clickable
  // token on the exploration map; clicking it (or "Talk to …") walks the party
  // marker to a free cell ADJACENT to the NPC and opens the conversation.
  // Omitted ⇒ no token (talk still works as a room-scoped choice).
  pos?: GridPos;
  // game-icons.net glyph name for this NPC's map token (e.g. 'wood-axe'). When
  // omitted the token uses a generic NPC glyph — a per-NPC override over that
  // default, mirroring how dungeon sites override DEFAULT_SITE_ICON.
  icon?: string;
  // Social
  greeting: string;
  // NPC narrative hooks, mirroring the level-hook pattern: the FIRST variant
  // overrides the plain one once. firstGreeting plays the first time the
  // party ever talks to this NPC (GameState.npc_talked); goodbye plays on
  // END CONVERSATION, with firstGoodbye overriding the first time
  // (GameState.npc_farewelled). All optional — greeting is the fallback,
  // and no goodbye means the generic "You end the conversation" line.
  firstGreeting?: string;
  goodbye?: string;
  firstGoodbye?: string;
  responses: NpcDialogueResponse[];
  persuasionDC?: number; // CHA check DC when indifferent (default 12)
  // Trade
  shop?: NpcShopEntry[];
  // Associates the NPC's shop with a faction so price modifiers can apply
  // (campaignEngine.factionShopPrice). Optional — NPCs without a faction
  // tag charge their static shop entry price.
  factionId?: string;
}

export interface NpcDialogueResponse {
  label: string;
  reply?: string; // NPC's follow-up text after player picks this
  consequences?: GameConsequence[]; // applied when this response is chosen
  // Visibility gate — a json-rules-engine condition (the same shape as
  // QuestStep.condition) evaluated against CampaignFacts. A response whose
  // condition does not hold is HIDDEN — never grayed out, never hinted at —
  // so gated paths stay a surprise for players who earn them. Evaluation
  // fails closed: a malformed condition hides the option.
  condition?: object;
  // One-shot — once chosen, the option disappears for the REST OF THE
  // PLAYTHROUGH (recorded in GameState.dialogue_chosen, which persists with
  // the session like objects_searched). On a `check` node the attempt is
  // what's spent — set it for one-chance gambits, omit it to allow retries.
  once?: boolean;
  // Skill-gated branch — picking it rolls a CHA-based social check (SRD:
  // Persuasion / Deception / Intimidation) against the DC. The outcome picks
  // the reply and fires the matching consequence list; children (`responses`)
  // open ONLY on success. A check node uses successReply/failReply INSTEAD of
  // `reply` and onSuccess/onFail INSTEAD of `consequences`.
  check?: {
    skill: 'persuasion' | 'deception' | 'intimidation';
    dc: number;
    successReply: string;
    failReply: string;
    onSuccess?: GameConsequence[];
    onFail?: GameConsequence[];
  };
  // Nested follow-up options. A response WITH children is a branch: picking it
  // descends a level (its `reply` becomes the new prompt, `responses` the new
  // options) and a "Back" choice appears. A response WITHOUT children is a leaf:
  // picking it plays its reply and keeps the current options.
  responses?: NpcDialogueResponse[];
}

export interface PlacedNpc extends NpcTemplate {
  roomId: string;
}

// ─── Campaign geography ──────────────────────────────────────────────

// ─── Quests + factions (skeleton) ────────────────────────────────────

export interface QuestStep {
  id: string;
  desc: string;
  condition: object; // json-rules-engine TopLevelCondition against CampaignFacts
}

export interface FactionThresholds {
  hostile: number;
  unfriendly: number;
  neutral: number;
  friendly: number;
  // SRD 5.2.1 (Allies & Organisations): the 5th tier above `friendly`.
  // Used by campaign data (grove_of_thorns) and rendered in
  // CampaignPanel; both were referencing this field while the type
  // omitted it — surfaced by the type-share move.
  exalted: number;
}

// ─── Character creation ──────────────────────────────────────────────

export interface Background {
  id: string;
  name: string;
  desc: string;
  skillProficiencies: string[]; // 2 skill names (e.g. 'Perception', 'Stealth')
  // Most backgrounds grant one tool proficiency, but several context
  // backgrounds (Outlander, Soldier, etc.) intentionally omit it.
  // Optional so contexts don't have to pass an explicit `null`.
  toolProficiency?: string | null;
  feature: string;
  featureDesc: string;
  // SRD additions. Optional so legacy context backgrounds
  // continue to work; new backgrounds should set them.
  /**
   * Origin feat granted automatically at character creation. References
   * a feat id in `Context.featTable`. The SRD lists one origin
   * feat per background (e.g. Acolyte → Magic Initiate, Farmer → Tough).
   */
  originFeat?: string;
  /**
   * Three abilities the background's +1/+1/+1 or +2/+1 ability score
   * bonus may go into. Display + validation only — players supply
   * final stats at character creation (`stats: { str, dex, ... }`),
   * and the engine doesn't re-apply this delta. Future PRs that move
   * stat-pick UX to the FE will consult this list.
   */
  abilityScoreIncreases?: AbilityKey[];
  /**
   * Item ids granted at character creation in addition to
   * `classStartingLoot`. Empty / undefined → use class-only gear.
   */
  startingEquipment?: string[];
  /**
   * Additional language granted by the background.
   */
  language?: string;
}

// ─── Feats (SRD Chapter 5) ──────────────────────────────────────
//
// A feat is a chunk of mechanical effect a player chooses at
// character creation (origin feats), at ASI levels (general feats),
// at L19 (epic boon feats), or from a class feature (fighting-style
// feats). Some feats are "half-feats" that include a +1 ability
// score bump alongside their main effect.
//
// `effect` is a discriminated union so the engine dispatches feat
// behavior via the `kind` tag (see `services/feats.ts`). Adding a
// new feat is a data entry plus, if it introduces a new effect
// pattern, one new union variant + one new case in the dispatcher.
// Common patterns (passive HP, d20 reroll resource, ranged attack
// toggle, spell list extension, save proficiency) share existing
// kinds so most feats are pure data.

/**
 * Discriminated union of feat effect shapes. Each `kind` corresponds
 * to a dispatch case in `services/feats.ts`. When adding a feat that
 * doesn't fit any existing kind, add a new variant and the matching
 * dispatcher case.
 */
export type FeatEffect =
  | {
      // Alert feat (SRD 5.2.1 origin) — +proficiency bonus to
      // Initiative rolls AND immunity to the Surprised condition.
      // The third Alert benefit (swap initiative with an ally) is
      // deferred — needs an explicit action and a swap window the
      // engine doesn't model yet.
      kind: 'alert';
    }
  | {
      // Savage Attacker feat (SRD 5.2.1 origin) — once per turn,
      // when you hit with a weapon's damage roll, you can reroll
      // the damage and use either total. Engine auto-takes the
      // higher of the two and marks
      // `turn_actions.savage_attacker_used`. Reset at turn start.
      kind: 'savage-attacker';
    }
  | {
      // Magic Initiate (SRD 5.2.1 origin) — extra cantrips + one L1
      // spell from a chosen class list, cast 1×/long rest without
      // slot. Pansori splits the choose-list step into three feat
      // IDs (arcane / divine / primal) so the picker surface is one
      // button per option rather than a take-then-pick workflow.
      kind: 'extra-cantrips-and-l1';
      spellList: 'arcane' | 'divine' | 'primal';
      cantripCount: number;
      l1Count: number;
    }
  | {
      // Skilled feat (SRD 5.2.1 origin) — gain proficiency in three
      // skills of your choice. The take handler reads
      // `opts.skillChoices` (3 entries) and merges them into
      // `char.skill_proficiencies`.
      kind: 'skill-proficiencies';
      count: number;
    }
  | {
      // Epic Boon feats (SRD 5.2.1, L19+). Every boon grants +1 to an
      // ability (via `abilityBonus`, capped at 30 for epic boons) plus a
      // signature benefit keyed by `boon`. Take-time applies only passive
      // grants (e.g. Truesight's range); the active benefits fire from
      // their own runtime hooks (attack resolution, casting, the D20-test
      // reaction path, the damage-resistance chain).
      kind: 'epic-boon';
      boon:
        | 'combat-prowess' // Peerless Aim — turn a miss into a hit, 1/turn
        | 'dimensional-travel' // Blink Steps — teleport 30 ft after Attack/Magic
        | 'fate' // Improve Fate — ±2d4 to a D20 Test within 60 ft, 1/rest
        | 'irresistible-offense' // Overcome Defenses + Overwhelming Strike
        | 'spell-recall' // Free Casting — 1d4 slot refund on L1–4 casts
        | 'night-spirit' // Merge with Shadows + Shadowy Form
        | 'truesight'; // Truesight 60 ft
    };

/**
 * Static data shape for a feat. Lives in `context.featTable` keyed by
 * `id`. Players reference feats by id on `Character.feats`.
 */
export interface Feat {
  id: string;
  name: string;
  desc: string;
  category: 'origin' | 'general' | 'fighting-style' | 'epic-boon';
  /**
   * Half-feats grant a +1 ability bump alongside their main effect.
   * - `{ fixed: 'con' }` — always +1 CON (e.g. Durable).
   * - `{ choices: ['str', 'con'] }` — player picks one at take time.
   * Absent → not a half-feat.
   */
  abilityBonus?: { fixed: AbilityKey } | { choices: AbilityKey[] };
  prerequisites?: {
    minLevel?: number;
    minAbilityScores?: Partial<Record<AbilityKey, number>>;
    classes?: string[];
    requiredFeat?: string;
    // Display-only prereq strings the engine doesn't model explicitly
    // ("Spellcasting feature", "Proficiency with martial weapons").
    other?: string[];
  };
  effect: FeatEffect;
}

// ─── Quests + factions (full bodies) ─────────────────────────────────

export interface Quest {
  id: string;
  title: string;
  desc: string;
  giverNpcId?: string;
  steps: QuestStep[];
  rewards: GameConsequence[];
  factionId?: string;
  repGain?: number;
  // The campaign's opening quest — seeded as `active` at session start so the
  // player begins with direction. All other quests stay hidden from the quest
  // log until discovered (their first step fires, auto-activating them).
  startActive?: boolean;
}

export interface QuestProgress {
  questId: string;
  status: QuestStatus;
  completedSteps: string[];
}

export interface Faction {
  id: string;
  name: string;
  thresholds: FactionThresholds;
  shopPriceModifiers: Record<string, number>; // attitude tier → price multiplier
}

// ─── Campaign state (persisted across sessions) ──────────────────────

export interface CampaignState {
  campaign_id: string;
  user_id: string;
  // In-game clock carried across sessions (total elapsed in-world minutes since
  // campaign start; Day 1 08:00 == 480). Resuming a session resumes the clock.
  world_minute: number;
  current_location: string;
  flags: Record<string, boolean | string | number>;
  quests: QuestProgress[];
  faction_rep: Record<string, number>;
  npc_attitudes: Record<string, NpcAttitude>;
}

// ─── Loot ────────────────────────────────────────────────────────────

// Equipment slots a character can fill. 5e has no formal body-slot system, so
// this is pansori's model: two hands (a two-handed weapon fills `main_hand`; a
// shield occupies `shield`), one suit of armor, and the worn wondrous-item
// slots. A character's `equipment` maps each filled slot to an inventory
// `instance_id`.
export type EquipSlot =
  | 'main_hand'
  | 'off_hand'
  | 'armor'
  | 'shield'
  | 'head'
  | 'neck'
  | 'cloak'
  | 'hands'
  | 'arms'
  | 'waist'
  | 'feet'
  | 'ring_1'
  | 'ring_2'
  | 'quiver';

export const EQUIP_SLOTS: EquipSlot[] = [
  'main_hand',
  'off_hand',
  'armor',
  'shield',
  'head',
  'neck',
  'cloak',
  'hands',
  'arms',
  'waist',
  'feet',
  'ring_1',
  'ring_2',
  'quiver',
];

// The body-slot *category* an item declares (LootItem.slot). 'weapon' maps to
// the main hand and 'ring' to whichever ring slot is free; every other value
// maps 1:1 to the EquipSlot of the same name. Distinct from EquipSlot because
// an item doesn't know which of the two ring slots it'll land in.
export type ItemSlot =
  | 'weapon'
  | 'off_hand'
  | 'armor'
  | 'shield'
  | 'head'
  | 'neck'
  | 'cloak'
  | 'hands'
  | 'arms'
  | 'waist'
  | 'feet'
  | 'ring'
  | 'quiver';

/**
 * A passive effect an item confers while WORN in its body slot (and attuned, if
 * the item requires attunement). A small discriminated union:
 *   - `save_bonus`: flat bonus to saves of an ability (e.g. Moonstone Amulet +1 WIS).
 *   - `light`: the item sheds light — its bearer emits a `radiusFt` bright-light
 *     radius (dim to 2×) in combat, negating the darkness penalty around them.
 *     Mundane (no spell level), so magical Darkness can't dispel it. Synced onto
 *     the bearer's combat entity at combat-start seeding, like the Light cantrip.
 * Extend the union as new worn-item mechanics land.
 */
export type WornEffect =
  | { kind: 'save_bonus'; ability: AbilityKey; bonus: number }
  | { kind: 'light'; radiusFt: number };

export interface LootItem {
  id: string;
  name: string;
  desc: string;
  weight: number;
  type: 'weapon' | 'armor' | 'consumable' | 'misc';
  slot: ItemSlot | null;
  damage: string | null;
  finesse?: boolean;
  range?: 'melee' | 'ranged';
  ac_bonus: number | null;
  heal: string | null;
  effect: string | null;
  aliases: string[];
  useNarrative?: string;
  armorCategory?: 'light' | 'medium' | 'heavy' | 'shield';
  weaponType?: 'simple' | 'martial';
  light?: boolean; // TWF: can be used in off-hand with another light weapon
  requiresAttunement?: boolean; // magic items requiring attunement
  // Passive effects this item confers while WORN in its body slot (and attuned,
  // if requiresAttunement). Applied by the worn-effects layer — see
  // services/wornEffects.ts. Distinct from `effect` (the consumable-use string).
  wornEffects?: WornEffect[];
  /**
   * Cursed item flag (SRD). The curse reveals on attunement and
   * voluntary de-attunement is blocked — only Remove Curse / Greater
   * Restoration / equivalent magic can break the bond. Pansori doesn't
   * yet implement those spells, so cursed items are effectively
   * permanent for now; the flag is in place for when remove-curse lands.
   */
  cursed?: boolean;
  /**
   * Display text shown when the curse reveals on attunement. Empty / undefined
   * → a generic fallback narrative is used.
   */
  curseDesc?: string;
  armorAcBase?: number; // base AC of armor when worn (e.g. leather=11, chain mail=16)
  dexCapToAc?: number; // max DEX bonus added to AC (2=medium, 0=heavy; undefined=full DEX)
  versatileDamage?: string; // two-handed damage for versatile weapons (e.g. '1d8' for quarterstaff)
  damageType?: string; // piercing / slashing / bludgeoning / fire / etc.
  thrown?: { normalRange: number; longRange: number }; // melee weapon usable as ranged
  // SRD 5.2.1 "Loading": one shot per Action/Bonus/Reaction regardless of
  // Extra Attack. Hand/heavy crossbows, muskets, pistols, blowguns all have it.
  loading?: boolean;
  // SRD 5.2.1 "Reach": adds 5 ft to melee reach (also for opportunity
  // attacks made with this weapon). Glaive, halberd, lance, pike, whip.
  reach?: boolean;
  // SRD 5.2.1 "Heavy": disadv on attacks if STR < 13 (melee) / DEX < 13
  // (ranged). Greataxe, greatsword, maul, heavy crossbow, longbow, etc.
  heavy?: boolean;
  // SRD Weapon Mastery property. Each weapon has at most one mastery.
  // Only applies when the wielder's class grants Weapon Mastery AND they
  // have mastered this specific weapon (Character.weaponMasteries).
  mastery?: WeaponMastery;
  // SRD thrown splash weapon (Acid vial, Alchemist's Fire, Holy Water). The
  // `throw_item` action makes a DEX ranged attack vs the target's AC; on a hit
  // it deals `damage` of `damageType`. `vsCreatureTypes` (Holy Water) restricts
  // the damage to matching `Enemy.creatureType`; `burn` (Alchemist's Fire) sets
  // the target alight for that recurring fire die (save-ends DC 10 DEX).
  splash?: {
    damage: string;
    damageType: string;
    vsCreatureTypes?: string[];
    burn?: string;
  };
  // Default stack size for a stackable item (ammunition — e.g. a bundle of 20
  // Arrows). Carried onto the inventory item; ranged attacks decrement it.
  count?: number;
}

/**
 * A loot item placed in a room. Rooms hold a list of these (`Seed.loot` is
 * `Record<roomId, PlacedLoot[]>`). `pos` is the grid cell on the local-room map
 * — when set the item renders as a clickable token and its "Pick up" choice is
 * gated on the party being adjacent. `key` is a stable per-placement identity
 * (distinct from the item `id`, which can repeat) used for the `loot_taken`
 * gate; when unauthored the engine derives `${roomId}#${index}`.
 */
export interface PlacedLoot extends LootItem {
  pos?: GridPos;
  key?: string;
}

// ─── Reactive-spell pause shapes ─────────────────────────────────────
//
// When an enemy-on-PC attack hits a reactive-spell trigger (Shield
// before damage, Hellish Rebuke after damage, Counterspell before the
// enemy spell resolves), the engine stashes a PendingReaction with
// enough state to resume the enemy-turn loop after the player decides.

interface PendingReactionBase {
  attackerEnemyId: string;
  targetCharId: string;
  resumeFromInitiativeIdx: number;
  resumeFromMultiattackIdx: number; // 0-indexed; how many sub-attacks already resolved
  narrativeSoFar: string;
  eligibleCharIds: string[];
}

// Shield (SRD). Triggers BEFORE damage applies — accepting negates the
// hit retroactively. The BE stashes a pre-computed proposed snapshot
// (fragment + char + state) so a decline commits them as-rolled and an
// accept discards them — including the concentration-save outcome that
// was rolled at attack time. Discard on accept is the RAW-correct
// behavior: one save per damage TAKEN, not per damage threatened.
//
// `pendingFragment` / `pendingProposedChar` / `pendingProposedSt` are
// typed as `unknown` here because their full shapes (EnemyAttackHitFragment,
// Character, GameState) live in BE-only modules (`services/narrative/
// fragments.ts` and the BE Character/GameState definitions); the FE
// doesn't introspect them — it just round-trips the pending_reaction
// state. BE narrows via cast.
export interface PendingShieldReaction extends PendingReactionBase {
  kind: 'shield';
  atkTotal: number; // to-hit total that triggered the [AC, AC+4] window
  targetAcAtAttack: number;
  pendingFragment: unknown;
  pendingProposedChar: unknown;
  pendingProposedSt: unknown;
}

// Hellish Rebuke (SRD). Triggers AFTER damage applies — accepting deals
// 2d10 fire damage back to the attacker (DEX save for half). No state to
// stash: the damage that triggered Rebuke is already on the books, and a
// decline just lets the enemy turn continue.
export interface PendingHellishRebukeReaction extends PendingReactionBase {
  kind: 'hellish_rebuke';
}

// Uncanny Dodge (SRD Rogue L5). Triggers BEFORE damage commits when
// the Rogue can see the attacker — accepting halves the damage from
// that one attack. Pre-built proposed snapshot is stashed the same
// way as Shield: accept ⇒ halve damage in the snapshot, commit;
// decline ⇒ commit the full-damage snapshot. Same proposed-state
// `unknown` typing as Shield (BE narrows via cast).
export interface PendingUncannyDodgeReaction extends PendingReactionBase {
  kind: 'uncanny_dodge';
  atkTotal: number;
  /** Full proposed damage before halving — for narrative display. */
  proposedDamage: number;
  pendingFragment: unknown;
  pendingProposedChar: unknown;
  pendingProposedSt: unknown;
}

// Deflect Attacks (SRD Monk L3). Triggers BEFORE damage commits when a
// Bludgeoning/Piercing/Slashing attack hits the Monk — accepting reduces the
// damage by 1d10 + DEX mod + Monk level (rolled in the resolver). Same
// pre-built proposed-snapshot stash as Uncanny Dodge: accept ⇒ reduce the
// damage in the snapshot, commit; decline ⇒ commit the full-damage snapshot.
export interface PendingDeflectReaction extends PendingReactionBase {
  kind: 'deflect_attacks';
  atkTotal: number;
  /** Full proposed damage before reduction — for narrative display + the
   *  resolver's reduction floor. */
  proposedDamage: number;
  pendingFragment: unknown;
  pendingProposedChar: unknown;
  pendingProposedSt: unknown;
}

// Save-reroll (SRD Fighter Indomitable / Bard Countercharm). Triggers AFTER a
// save-based onHitEffect condition lands — accepting rerolls the failed save
// (the outcome is pre-rolled at trigger time) and, on success, removes the
// condition. Indomitable isn't a Reaction (just a per-rest reroll); Countercharm
// spends the bard's Reaction. The reactor (`reactorCharId`) may differ from the
// condition-holder (`targetCharId`) when an ally bard Countercharms.
export interface PendingSaveRerollReaction extends PendingReactionBase {
  kind: 'save_reroll';
  source: 'indomitable' | 'countercharm';
  /** Who spends the reroll (target for Indomitable, the bard for Countercharm). */
  reactorCharId: string;
  reactorName: string;
  /** A successful reroll either removes `condition` from `targetCharId`
   *  (condition-save path), refunds `damageRefund` HP (damage-save path), or
   *  keeps the `concentrationSpellId` spell (concentration path — where the
   *  break is deferred, so decline / a failed reroll breaks it). One is set. */
  condition?: string;
  damageRefund?: number;
  concentrationSpellId?: string;
  saveAbility: string;
  saveDc: number;
  /** Pre-rolled at trigger time — applied on accept. */
  rerollSucceeds: boolean;
}

// Counterspell (SRD). Triggers BEFORE the enemy spell resolves —
// accepting consumes a slot on the PC and negates the enemy spell.
export interface PendingCounterspellReaction extends PendingReactionBase {
  kind: 'counterspell';
  enemySpellId: string;
  enemySpellLevel: number; // base level of the enemy's spell (slot level not modeled enemy-side)
  enemySpellName: string; // pre-fetched so generateChoices doesn't need the spellTable
  // PC the enemy spell would hit if not countered. Resolved at trigger time
  // (usually nearest PC) and stored so a decline branch can apply damage
  // without re-running target selection.
  intendedTargetPcId: string;
}

// SRD PC-turn d20 reaction window. Fires when a PC rolls a d20
// for an attack roll (initial scope; saves + ability checks land next)
// and the engine should pause to offer post-roll reactions before
// committing the outcome. Distinct base from PendingReactionBase
// because the roller is a PC and the eligible reactor is usually the
// roller themselves (Heroic Inspiration is a self-reaction). The
// enemy-attack base (`attackerEnemyId` + `targetCharId`) doesn't
// match this shape.
//
// First wiring: Heroic Inspiration (SRD: "expend it to reroll any die
// immediately after rolling it, and you must use the new roll").
// Future plug-ins:
//   - Lucky feat (PHB-only; spend a luck point after roll)
//   - Clockwork Soul Restore Balance (cancel adv/disadv on any d20)
//   - Other post-roll dice-modifier reactions
//
// `accept` re-resolves the action with a new d20 (RAW: must use new);
// `decline` commits the proposed snapshot as-rolled.
export interface PendingPcD20Reaction {
  kind: 'pc_d20';
  /** The primary feature offering the reaction (informational — the choice
   *  surface offers every feature the roller has available). */
  source: 'inspiration' | 'stroke_of_luck';
  /** PC who rolled the original d20 + (initial scope) who reacts. */
  rollerCharId: string;
  /** What kind of d20 roll the PC made.
   *  - 'attack': shipped — pause in attack/index.ts after the first
   *    resolveOneAttack, rewind on accept, re-call with forced d20.
   *  - 'save': deferred plug-in. Pause point lives in the function
   *    that rolls the save (e.g. checkConcentration, the death-save
   *    branch in gameEngine, or any spell-save site). Each site
   *    needs its own rewind/resume since the consequences of a
   *    failed save differ (concentration drop, condition apply,
   *    death-save accumulator, etc.).
   *  - 'check': deferred plug-in. Same shape as 'save' but for
   *    ability checks (skill checks via skillCheck, the sneak
   *    Stealth contest, trap-disarm checks, etc.). */
  rollContext: 'attack' | 'save' | 'check';
  /** The d20 face that was rolled (1-20). */
  originalD20: number;
  /** Original total (d20 + mods). For narrative. */
  originalTotal: number;
  /** Did the original roll hit? Pansori MVP only pauses on miss. */
  originalHit: boolean;
  /** Eligible reactor ids — initial scope is self only. */
  eligibleCharIds: string[];
  /** Attack-context fields needed to inline-re-resolve on accept.
   *  Typed as `unknown` because the FE doesn't introspect; BE narrows. */
  attackContext: unknown;
  /** State to commit on decline (the as-rolled miss). */
  pendingProposedChar: unknown;
  pendingProposedSt: unknown;
  /** Initiative resume anchor. Pansori MVP only pauses after the FIRST
   *  attack (Extra Attack iterations are not paused — they continue
   *  after the reaction resolves). */
  resumeFromInitiativeIdx: number;
}

export type PendingReaction =
  | PendingShieldReaction
  | PendingHellishRebukeReaction
  | PendingCounterspellReaction
  | PendingUncannyDodgeReaction
  | PendingDeflectReaction
  | PendingSaveRerollReaction
  | PendingPcD20Reaction;
